// src/hooks/useLanguage.ts
import { useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'tr' | 'ku' | 'de' | 'es' | 'ru' | 'fr' | 'it';

interface Translations {
  [key: string]: {
    [key in LanguageCode]: string;
  };
}

const translations: Translations = {
  // ===== Navigation (Landing) =====
  welcome: {
    en: 'Welcome to GroveML',
    tr: "GroveML'e Hoş Geldiniz",
    ku: 'Bi xêr hatin GroveML',
    de: 'Willkommen bei GroveML',
    es: 'Bienvenido a GroveML',
    ru: 'Добро пожаловать в GroveML',
    fr: 'Bienvenue sur GroveML',
    it: 'Benvenuto in GroveML',
  },
  subtitle: {
    en: 'Build powerful machine learning models without writing a single line of code',
    tr: 'Tek satır kod yazmadan güçlü makine öğrenmesi modelleri oluşturun',
    ku: 'Bêyî ku yek rêzik kod binivîsî, modelên hînbûna makîneyê yên xurt çêbikin',
    de: 'Erstellen Sie leistungsstarke Machine-Learning-Modelle ohne eine einzige Codezeile zu schreiben',
    es: 'Construye modelos de aprendizaje automático potentes sin escribir una sola línea de código',
    ru: 'Создавайте мощные модели машинного обучения без написания единой строки кода',
    fr: "Construisez des modèles d'apprentissage automatique puissants sans écrire une seule ligne de code",
    it: 'Costruisci potenti modelli di machine learning senza scrivere una singola riga di codice',
  },
  getStarted: {
    en: 'Get Started',
    tr: 'Başla',
    ku: 'Dest pê bike',
    de: 'Loslegen',
    es: 'Comenzar',
    ru: 'Начать',
    fr: 'Commencer',
    it: 'Inizia',
  },
  noCodeRequired: {
    en: 'No Code Required',
    tr: 'Kod Gerektirmez',
    ku: 'Kod pêwîst nake',
    de: 'Kein Code erforderlich',
    es: 'No se requiere código',
    ru: 'Код не требуется',
    fr: 'Aucun code requis',
    it: 'Nessun codice richiesto',
  },
  noCodeDescription: {
    en: 'Build ML models with intuitive drag-and-drop interface',
    tr: 'Sezgisel sürükle-bırak arayüzü ile ML modelleri oluşturun',
    ku: 'Bi navberê sade û hêsan modelên ML çêbikin',
    de: 'Erstellen Sie ML-Modelle mit intuitiver Drag-and-Drop-Oberfläche',
    es: 'Construye modelos ML con interfaz intuitiva de arrastrar y soltar',
    ru: 'Создавайте ML модели с интуитивным интерфейсом перетаскивания',
    fr: 'Construisez des modèles ML avec une interface glisser-déposer intuitive',
    it: 'Costruisci modelli ML con interfaccia intuitiva drag-and-drop',
  },
  lightningFast: {
    en: 'Lightning Fast',
    tr: 'Şimşek Hızında',
    ku: 'Zû wek birûsk',
    de: 'Blitzschnell',
    es: 'Súper Rápido',
    ru: 'Молниеносно',
    fr: 'Ultra Rapide',
    it: 'Veloce come un fulmine',
  },
  lightningFastDescription: {
    en: 'Process your data and train models in minutes, not hours',
    tr: 'Verilerinizi işleyin ve modelleri saatler değil dakikalar içinde eğitin',
    ku: 'Daneyên xwe di deqeyan de pêvajo bikin, ne di seatên de',
    de: 'Verarbeiten Sie Ihre Daten und trainieren Sie Modelle in Minuten, nicht Stunden',
    es: 'Procesa tus datos y entrena modelos en minutos, no horas',
    ru: 'Обрабатывайте данные и обучайте модели за минуты, а не часы',
    fr: 'Traitez vos données et entraînez des modèles en minutes, pas en heures',
    it: 'Elabora i tuoi dati e addestra modelli in minuti, non ore',
  },
  productionReady: {
    en: 'Production Ready',
    tr: 'Üretime Hazır',
    ku: 'Amade ji bo hilberînê',
    de: 'Produktionsbereit',
    es: 'Listo para Producción',
    ru: 'Готово к продакшену',
    fr: 'Prêt pour la production',
    it: 'Pronto per la produzione',
  },
  productionReadyDescription: {
    en: 'Deploy your models with enterprise-grade reliability',
    tr: 'Modellerinizi kurumsal düzeyde güvenilirlikle dağıtın',
    ku: 'Modelên xwe bi pêbaweriya pîşesî bicîh bikin',
    de: 'Stellen Sie Ihre Modelle mit Unternehmens-Zuverlässigkeit bereit',
    es: 'Despliega tus modelos con confiabilidad empresarial',
    ru: 'Развертывайте модели с корпоративной надежностью',
    fr: 'Déployez vos modèles avec une fiabilité d’entreprise',
    it: 'Distribuisci i tuoi modelli con affidabilità aziendale',
  },

  // ===== Step Names =====
  upload: { en: 'Upload', tr: 'Yükle', ku: 'Bar bike', de: 'Hochladen', es: 'Subir', ru: 'Загрузить', fr: 'Télécharger', it: 'Carica' },
  analyze: { en: 'Analyze', tr: 'Analiz Et', ku: 'Analîz bike', de: 'Analysieren', es: 'Analizar', ru: 'Анализировать', fr: 'Analyser', it: 'Analizza' },
  missingValues: { en: 'Missing Values', tr: 'Eksik Değerler', ku: 'Nirxên winda', de: 'Fehlende Werte', es: 'Valores Faltantes', ru: 'Пропущенные значения', fr: 'Valeurs manquantes', it: 'Valori mancanti' },
  detectOutliers: { en: 'Detect Outliers', tr: 'Aykırı Değerleri Tespit Et', ku: 'Nirxên cuda nas bike', de: 'Ausreißer erkennen', es: 'Detectar Valores Atípicos', ru: 'Обнаружить выбросы', fr: 'Détecter les valeurs aberrantes', it: 'Rileva valori anomali' },
  removeOutliers: { en: 'Remove Outliers', tr: 'Aykırı Değerleri Temizle', ku: 'Nirxên cuda rake', de: 'Ausreißer entfernen', es: 'Eliminar Valores Atípicos', ru: 'Удалить выбросы', fr: 'Supprimer les valeurs aberrantes', it: 'Rimuovi valori anomali' },
  encoding: { en: 'Encoding', tr: 'Kodlama', ku: 'Kodkirin', de: 'Kodierung', es: 'Codificación', ru: 'Кодирование', fr: 'Encodage', it: 'Codifica' },
  correlation: { en: 'Correlation', tr: 'Korelasyon', ku: 'Têkilî', de: 'Korrelation', es: 'Correlación', ru: 'Корреляция', fr: 'Corrélation', it: 'Correlazione' },
  targetCorrelation: { en: 'Target Correlation', tr: 'Hedef Korelasyonu', ku: 'Têkiliya armancê', de: 'Ziel-Korrelation', es: 'Correlación Objetivo', ru: 'Корреляция цели', fr: 'Corrélation cible', it: 'Correlazione target' },
  scaling: { en: 'Scaling', tr: 'Ölçeklendirme', ku: 'Pîvandin', de: 'Skalierung', es: 'Escalado', ru: 'Масштабирование', fr: "Mise à l'échelle", it: 'Ridimensionamento' },
  training: { en: 'Training', tr: 'Eğitim', ku: 'Perwerdehî', de: 'Training', es: 'Entrenamiento', ru: 'Обучение', fr: 'Entraînement', it: 'Addestramento' },
  evaluation: { en: 'Evaluation', tr: 'Değerlendirme', ku: 'Nirxandin', de: 'Bewertung', es: 'Evaluación', ru: 'Оценка', fr: 'Évaluation', it: 'Valutazione' },
  optimization: { en: 'Optimization', tr: 'Optimizasyon', ku: 'Baştirkirin', de: 'Optimierung', es: 'Optimización', ru: 'Оптимизация', fr: 'Optimisation', it: 'Ottimizzazione' },

  // ===== Common UI =====
  dataPreview: {
    en: 'Data Preview',
    tr: 'Veri Önizlemesi',
    ku: 'Pêşdîtina daneyan',
    de: 'Datenvorschau',
    es: 'Vista previa de datos',
    ru: 'Предварительный просмотр данных',
    fr: 'Aperçu des données',
    it: 'Anteprima dati',
  },
  continue: { en: 'Continue', tr: 'Devam Et', ku: 'Bidomîne', de: 'Weiter', es: 'Continuar', ru: 'Продолжить', fr: 'Continuer', it: 'Continua' },
  apply: { en: 'Apply', tr: 'Uygula', ku: 'Bicîh bike', de: 'Anwenden', es: 'Aplicar', ru: 'Применить', fr: 'Appliquer', it: 'Applica' },
  skip: { en: 'Skip', tr: 'Atla', ku: 'Derbas bike', de: 'Überspringen', es: 'Omitir', ru: 'Пропустить', fr: 'Ignorer', it: 'Salta' },
  previous: { en: 'Previous', tr: 'Önceki', ku: 'Berê', de: 'Zurück', es: 'Anterior', ru: 'Назад', fr: 'Précédent', it: 'Precedente' },
  next: { en: 'Next', tr: 'Sonraki', ku: 'Pêş', de: 'Weiter', es: 'Siguiente', ru: 'Далее', fr: 'Suivant', it: 'Avanti' },

  // Useful small words
  results: { en: 'Results', tr: 'Sonuçlar', ku: 'Encam', de: 'Ergebnisse', es: 'Resultados', ru: 'Результаты', fr: 'Résultats', it: 'Risultati' },
  to: { en: 'to', tr: '→', ku: 'bo', de: 'zu', es: 'a', ru: 'к', fr: 'vers', it: 'a' },
  model: { en: 'Model', tr: 'Model', ku: 'Model', de: 'Modell', es: 'Modelo', ru: 'Модель', fr: 'Modèle', it: 'Modello' },
  format: { en: 'Format', tr: 'Format', ku: 'Format', de: 'Format', es: 'Formato', ru: 'Формат', fr: 'Format', it: 'Formato' },
  cancel: { en: 'Cancel', tr: 'İptal', ku: 'Betal', de: 'Abbrechen', es: 'Cancelar', ru: 'Отмена', fr: 'Annuler', it: 'Annulla' },
  export: { en: 'Export', tr: 'Dışa Aktar', ku: 'Derxistin', de: 'Exportieren', es: 'Exportar', ru: 'Экспорт', fr: 'Exporter', it: 'Esporta' },
  exporting: { en: 'Exporting…', tr: 'Dışa aktarılıyor…', ku: 'Tê derxistin…', de: 'Exportiere…', es: 'Exportando…', ru: 'Экспорт…', fr: 'Export…', it: 'Esportazione…' },

  // ===== Info tooltips (Analysis/common) =====
  infoDataPreview: {
    en: 'Preview of the working dataset. Hover a column header to reveal the trash icon and drop that column.',
    tr: 'Çalışma veri kümesinin önizlemesi. Sütun başlığına gelince çöp kutusu görünür; tıklayarak o sütunu kaldırabilirsiniz.',
    ku: 'Pêşdîtina daneyên xebatê. Li ser sernavê stûnê bi hoverê îkona avêtinê dixuye; bi tikandina wê stûnê rake.',
    de: 'Vorschau des Arbeits-Datensatzes. Über einer Spaltenüberschrift schweben, um das Papierkorb-Symbol einzublenden und die Spalte zu löschen.',
    es: 'Vista previa del conjunto de datos en uso. Pasa el cursor por el encabezado de una columna para mostrar el icono de papelera y eliminar esa columna.',
    ru: 'Предпросмотр рабочего набора данных. Наведите на заголовок столбца, чтобы показать значок корзины и удалить столбец.',
    fr: "Aperçu du jeu de données courant. Survolez un en-tête de colonne pour afficher l'icône corbeille et supprimer la colonne.",
    it: "Anteprima del dataset in uso. Passa il mouse sull'intestazione di una colonna per mostrare l'icona cestino ed eliminare la colonna.",
  },

  // ===== Missing Values (tooltips) =====
  infoMissingValuesTotal: {
    en: 'Total number of missing cells across the dataset.',
    tr: 'Veri kümesindeki toplam eksik hücre sayısı.',
    ku: 'Hejmara tevahî ya xaneyan ên winda di daneyên de.',
    de: 'Gesamtzahl fehlender Zellen im Datensatz.',
    es: 'Número total de celdas faltantes en el conjunto de datos.',
    ru: 'Общее число пропущенных ячеек в наборе данных.',
    fr: 'Nombre total de cellules manquantes dans le jeu de données.',
    it: 'Numero totale di celle mancanti nel dataset.',
  },
  infoMemoryUsage: {
    en: 'Approximate in-memory size of the loaded dataset.',
    tr: 'Yüklü veri kümesinin yaklaşık bellek boyutu.',
    ku: 'Mezinahiya bîrê ya qiraxa daneyên barkirî.',
    de: 'Geschätzte Speicherbelegung des geladenen Datensatzes.',
    es: 'Tamaño aproximado en memoria del conjunto de datos cargado.',
    ru: 'Оценка объёма памяти, занимаемого загруженным набором данных.',
    fr: 'Taille en mémoire approximative du jeu de données chargé.',
    it: 'Dimensione in memoria (stimata) del dataset caricato.',
  },
  infoQualityScore: {
    en: '0–100 data quality score combining missingness, constant columns, ID-like fields and high-cardinality categoricals.',
    tr: 'Eksiklik, sabit sütunlar, kimlik benzeri alanlar ve yüksek kardinaliteli kategoriklerden türetilmiş 0–100 veri kalitesi skoru.',
    ku: 'Skora kalîteya daneyê 0–100 ku li ser winda-bûnê, stûnên sabît, qada wekî nasname û kategorîyên bi kardînalîteya bilind hate hesabkirin.',
    de: 'Datenqualitäts-Score (0–100) basierend auf Fehlwerten, konstanten Spalten, ID-ähnlichen Feldern und hochkardinalen Kategorien.',
    es: 'Puntuación de calidad de datos (0–100) que combina ausencias, columnas constantes, campos tipo ID y categóricas de alta cardinalidad.',
    ru: 'Оценка качества данных (0–100), учитывающая пропуски, постоянные столбцы, поля-идентификаторы и категориальные признаки с высокой кардинальностью.',
    fr: 'Score de qualité des données (0–100) combinant taux de valeurs manquantes, colonnes constantes, champs de type ID et catégorielles à forte cardinalité.',
    it: 'Punteggio di qualità dei dati (0–100) che combina valori mancanti, colonne costanti, campi simili a ID e categoriche ad alta cardinalità.',
  },
  infoConstantCols: {
    en: 'Columns that contain only a single unique value and add no information.',
    tr: 'Tek bir benzersiz değere sahip, bilgi taşımayan sütunlar.',
    ku: 'Stûnên ku tenê yek nirxa taybet hene û agahî nadin.',
    de: 'Spalten mit nur einem eindeutigen Wert – ohne Informationsgehalt.',
    es: 'Columnas con un único valor; no aportan información.',
    ru: 'Столбцы с единственным уникальным значением — не несут информации.',
    fr: "Colonnes ne contenant qu'une valeur unique — n'apportent pas d'information.",
    it: 'Colonne con un solo valore unico: non aggiungono informazione.',
  },
  infoHighCardCategoricals: {
    en: 'Categorical columns with very many unique values; often need encoding or feature reduction.',
    tr: 'Çok sayıda benzersiz değeri olan kategorik sütunlar; genellikle kodlama veya öznitelik indirgeme gerekir.',
    ku: 'Stûnên kategorîk ên bi nirxên pir; gelek caran kodkirin an kêmkirina taybetmendiyan hewce dike.',
    de: 'Kategorische Spalten mit sehr vielen Ausprägungen; oft Encoding oder Merkmalsreduktion nötig.',
    es: 'Columnas categóricas con muchos valores distintos; suelen requerir codificación o reducción de características.',
    ru: 'Категориальные столбцы с очень большим числом уникальных значений; часто требуют кодирования или уменьшения признаков.',
    fr: 'Colonnes catégorielles avec de très nombreuses modalités; nécessitent souvent un encodage ou une réduction de variables.',
    it: 'Colonne categoriche con moltissime modalità; spesso richiedono encoding o riduzione delle feature.',
  },
  infoMissingPairs: {
    en: 'Column pairs that tend to be missing together (co-missingness).',
    tr: 'Birlikte eksik olma eğilimindeki sütun çiftleri (eş-eksiklik).',
    ku: 'Du stûnên ku bi hev re winda dibin (co-missingness).',
    de: 'Spaltenpaare, die häufig gemeinsam fehlen.',
    es: 'Pares de columnas que tienden a faltar juntas.',
    ru: 'Пары столбцов, которые часто пропускаются одновременно.',
    fr: 'Paires de colonnes manquantes conjointement.',
    it: 'Coppie di colonne che tendono a mancare insieme.',
  },
  infoCramersV: {
    en: 'Association strength between two categorical variables (0–1).',
    tr: 'İki kategorik değişken arasındaki ilişki gücü (0–1).',
    ku: 'Hêza têkiliya di navbera du guhartoyên kategorîk de (0–1).',
    de: 'Stärke der Assoziation zwischen zwei kategorialen Variablen (0–1).',
    es: 'Fuerza de asociación entre dos variables categóricas (0–1).',
    ru: 'Сила связи между двумя категориальными переменными (0–1).',
    fr: "Force d'association entre deux variables catégorielles (0–1).",
    it: 'Forza di associazione tra due variabili categoriche (0–1).',
  },

  // ===== Missing Values step =====
  infoGlobalSettings: {
    en: 'Default imputation rules applied across all columns unless overridden below.',
    tr: 'Aşağıda özelleştirilmedikçe tüm sütunlara uygulanacak varsayılan atama kuralları.',
    ku: 'Rêbazên standard ên tije li hemû stûnan têne sepandin heya ku li jêr neyên guherandin.',
    de: 'Standard-Imputationsregeln für alle Spalten, sofern unten nicht überschrieben.',
    es: 'Reglas de imputación por defecto aplicadas a todas las columnas salvo que se anulen abajo.',
    ru: 'Правила заполнения по умолчанию для всех столбцов, если ниже не переопределены.',
    fr: "Règles d'imputation par défaut appliquées à toutes les colonnes sauf indication contraire ci-dessous.",
    it: 'Regole di imputazione predefinite applicate a tutte le colonne salvo override sotto.',
  },
  infoNumericStrategy: {
    en: 'How to fill missing values in numeric columns (e.g., mean, median, zero, forward/backward fill).',
    tr: 'Sayısal sütunlardaki eksikleri nasıl dolduracağınız (ör. ortalama, medyan, sıfır, ileri/geri doldurma).',
    ku: 'Çawa nirxên winda yên di stûnên hejmarî de tije bikin (mînak: navîn, medyan, sifir, ffill/bfill).',
    de: 'Vorgehen zum Füllen fehlender Werte in numerischen Spalten (z. B. Mittelwert, Median, 0, Forward/Backward Fill).',
    es: 'Cómo rellenar ausentes en columnas numéricas (p. ej., media, mediana, cero, forward/backward fill).',
    ru: 'Способ заполнения пропусков в числовых столбцах (среднее, медиана, ноль, прямое/обратное заполнение).',
    fr: 'Méthode de remplissage des valeurs manquantes numériques (moyenne, médiane, zéro, propagation avant/arrière).',
    it: 'Come riempire i mancanti nelle colonne numeriche (media, mediana, zero, forward/backward fill).',
  },
  infoCategoricalStrategy: {
    en: 'How to fill missing values in categorical columns (mode, constant token, forward/backward fill).',
    tr: 'Kategorik sütunlardaki eksikleri nasıl dolduracağınız (mod, sabit değer, ileri/geri doldurma).',
    ku: 'Rêbaza tijekirina winda yên di stûnên kategorîk de (mod, nirxa sabît, ffill/bfill).',
    de: 'Auffüllen fehlender Werte in kategorialen Spalten (Modus, fester Token, Forward/Backward Fill).',
    es: 'Relleno de ausentes en columnas categóricas (moda, valor constante, forward/backward fill).',
    ru: 'Заполнение пропусков в категориальных столбцах (мода, фиксированное значение, прямое/обратное заполнение).',
    fr: 'Remplissage des manquants catégoriels (mode, valeur constante, propagation avant/arrière).',
    it: 'Riempimento dei mancanti nelle categoriali (moda, valore fisso, forward/backward fill).',
  },
  infoDropStrategy: {
    en: 'Optional removal of rows or columns with missing values before imputation.',
    tr: 'Atama öncesinde eksik değer içeren satır veya sütunların isteğe bağlı olarak silinmesi.',
    ku: 'Bijartî: berî imputationê rêzik an stûnên bi winda-bûnê rakirin.',
    de: 'Optionales Entfernen von Zeilen/Spalten mit Fehlwerten vor der Imputation.',
    es: 'Eliminación opcional de filas/columnas con ausentes antes de la imputación.',
    ru: 'Необязательное удаление строк/столбцов с пропусками до импутации.',
    fr: "Suppression optionnelle des lignes/colonnes avec manquants avant l'imputation.",
    it: 'Rimozione opzionale di righe/colonne con mancanti prima dell’imputazione.',
  },
  infoColumnSpecific: {
    en: 'Override global rules for selected columns with custom strategies and values.',
    tr: 'Seçili sütunlar için genel kuralları özelleştirilmiş strateji ve değerlerle geçersiz kılın.',
    ku: 'Ji bo stûnên hilbijartî rêzên giştî bi stratejiyên taybet û nirxan biguherîne.',
    de: 'Globale Regeln für ausgewählte Spalten mit eigenen Strategien/Werten überschreiben.',
    es: 'Anula las reglas globales para columnas seleccionadas con estrategias y valores propios.',
    ru: 'Переопределение общих правил для выбранных столбцов с кастомными стратегиями и значениями.',
    fr: 'Outrepasser les règles globales pour certaines colonnes avec des stratégies/valeurs dédiées.',
    it: 'Sovrascrivi le regole globali per colonne selezionate con strategie e valori personalizzati.',
  },

  // ===== Outliers step =====
  infoDetectionSettings: {
    en: 'Parameters to identify outliers before applying fixes.',
    tr: 'Düzeltme uygulanmadan önce aykırıları belirlemek için kullanılan parametreler.',
    ku: 'Pêşî ji berê çarxebûnê, paramêtirên naskirina nirxên cuda.',
    de: 'Parameter zur Erkennung von Ausreißern vor der Behandlung.',
    es: 'Parámetros para identificar atípicos antes de corregir.',
    ru: 'Параметры для выявления выбросов перед обработкой.',
    fr: 'Paramètres pour identifier les valeurs aberrantes avant traitement.',
    it: 'Parametri per identificare outlier prima degli interventi.',
  },
  infoDetectMethod: {
    en: 'Algorithm used to score outliers (IQR, Z-Score or Auto).',
    tr: 'Aykırıları puanlamak için kullanılan algoritma (IQR, Z-Skor veya Otomatik).',
    ku: 'Algorîtma ji bo nirxandina outlier (IQR, Z-Score an Auto).',
    de: 'Algorithmus zur Bewertung von Ausreißern (IQR, Z-Score oder Auto).',
    es: 'Algoritmo para puntuar atípicos (IQR, Z-Score o Auto).',
    ru: 'Алгоритм для оценки выбросов (IQR, Z-Score или Auto).',
    fr: 'Algorithme pour scorer les valeurs aberrantes (IQR, Z-Score ou Auto).',
    it: 'Algoritmo per valutare outlier (IQR, Z-Score o Auto).',
  },
  infoDetectFactor: {
    en: 'Sensitivity of detection: higher values flag fewer points.',
    tr: 'Tespit hassasiyeti: değer büyüdükçe daha az nokta işaretlenir.',
    ku: 'Hessasî ya tesbîtê: nirxê bilind → nişanekirina kêmtir.',
    de: 'Empfindlichkeit: höhere Werte markieren weniger Punkte.',
    es: 'Sensibilidad: valores mayores marcan menos puntos.',
    ru: 'Чувствительность: чем выше значение, тем меньше точек помечается.',
    fr: 'Sensibilité : plus la valeur est élevée, moins de points signalés.',
    it: 'Sensibilità: valori maggiori segnalano meno punti.',
  },
  infoDetectionSummary: {
    en: 'Aggregate counts for detected outliers.',
    tr: 'Tespit edilen aykırılar için özet sayılar.',
    ku: 'Koma hejmarên outlierên hatine dizîn.',
    de: 'Aggregierte Kennzahlen der erkannten Ausreißer.',
    es: 'Conteos agregados de atípicos detectados.',
    ru: 'Сводные показатели по найденным выбросам.',
    fr: 'Totaux agrégés des valeurs aberrantes détectées.',
    it: 'Conteggi aggregati degli outlier rilevati.',
  },
  infoTotalOutliers: {
    en: 'Number of rows flagged as outliers across all numeric columns.',
    tr: 'Tüm sayısal sütunlar genelinde aykırı olarak işaretlenen satır sayısı.',
    ku: 'Hejmara rêzên ku wek outlier hatine nîşankirin.',
    de: 'Anzahl Zeilen, die als Ausreißer markiert wurden.',
    es: 'Filas marcadas como atípicas en total.',
    ru: 'Число строк, помеченных как выбросы.',
    fr: 'Nombre total de lignes signalées comme aberrantes.',
    it: 'Righe totali segnalate come outlier.',
  },
  infoAffectedColumns: {
    en: 'Count of columns that contain at least one detected outlier.',
    tr: 'En az bir aykırı içeren sütun sayısı.',
    ku: 'Hejmara stûnan ku herî kêm yek outlier hene.',
    de: 'Anzahl Spalten mit mindestens einem Ausreißer.',
    es: 'Número de columnas con al menos un atípico.',
    ru: 'Число столбцов с хотя бы одним выбросом.',
    fr: 'Colonnes contenant au moins une valeur aberrante.',
    it: 'Colonne con almeno un outlier.',
  },
  infoOutlierPercentage: {
    en: 'Share of rows flagged at least once during detection.',
    tr: 'Tespit sırasında en az bir kez işaretlenen satırların oranı.',
    ku: 'Rêza rêzên ku herî kêm carekê hatin nîşankirin.',
    de: 'Anteil der Zeilen, die mindestens einmal markiert wurden.',
    es: 'Porcentaje de filas marcadas al menos una vez.',
    ru: 'Доля строк, помеченных хотя бы один раз.',
    fr: 'Part des lignes signalées au moins une fois.',
    it: 'Quota di righe marcate almeno una volta.',
  },
  infoOutliersByColumn: {
    en: 'Distribution of detected outliers per column.',
    tr: 'Sütun başına tespit edilen aykırıların dağılımı.',
    ku: 'Belavbûna outlieran li gorî stûn.',
    de: 'Verteilung der Ausreißer je Spalte.',
    es: 'Distribución de atípicos por columna.',
    ru: 'Распределение выбросов по столбцам.',
    fr: 'Répartition des valeurs aberrantes par colonne.',
    it: 'Distribuzione degli outlier per colonna.',
  },
  infoRemovalSettings: {
    en: 'How detected outliers will be handled globally.',
    tr: 'Tespit edilen aykırıların genel düzeyde nasıl ele alınacağı.',
    ku: 'Çawa outlierên hatine dîtin bi şêwazê giştî têne şixulandin.',
    de: 'Wie erkannte Ausreißer global behandelt werden.',
    es: 'Cómo se tratarán globalmente los atípicos detectados.',
    ru: 'Как глобально обрабатывать найденные выбросы.',
    fr: 'Traitement global des valeurs aberrantes détectées.',
    it: 'Gestione globale degli outlier rilevati.',
  },
  infoRemovalStrategy: {
    en: 'Action to apply to outliers: remove, cap, replace with NaN, or impute.',
    tr: 'Aykırılara uygulanacak işlem: silme, sınırlandırma, NaN ile değiştirme veya imputasyon.',
    ku: 'Çalakî li ser outlier: jêbirin, sînorkirin, bi NaN guherandin an impute kirin.',
    de: 'Aktion für Ausreißer: entfernen, kappen, durch NaN ersetzen oder imputieren.',
    es: 'Acción sobre atípicos: eliminar, capar, reemplazar por NaN o imputar.',
    ru: 'Действие для выбросов: удалить, обрезать, заменить на NaN или импутировать.',
    fr: 'Action sur les valeurs aberrantes : supprimer, caper, remplacer par NaN ou imputer.',
    it: 'Azione sugli outlier: rimuovere, cappare, sostituire con NaN o imputare.',
  },
  infoRemovalMethod: {
    en: 'Rule for computing bounds used by capping/removal (IQR, Z-Score, Auto).',
    tr: 'Sınırları hesaplamak için kullanılan kural (IQR, Z-Skor, Otomatik).',
    ku: 'Rêbaz ji bo hesibandina sînorên cap/remove (IQR, Z-Score, Auto).',
    de: 'Regel zur Grenzberechnung für Kappung/Entfernung (IQR, Z-Score, Auto).',
    es: 'Regla para calcular límites en capado/eliminación (IQR, Z-Score, Auto).',
    ru: 'Правило расчёта границ для обрезки/удаления (IQR, Z-Score, Auto).',
    fr: 'Règle pour calculer les bornes de cap/suppression (IQR, Z-Score, Auto).',
    it: 'Regola per i limiti usati in capping/rimozione (IQR, Z-Score, Auto).',
  },
  infoRemovalFactor: {
    en: 'Sensitivity when applying the chosen handling (higher = fewer changes).',
    tr: 'Seçili işleme uygulanırken hassasiyet (yüksek = daha az müdahale).',
    ku: 'Hessasî di demê sepandina rêbazê de (bilindtir = guherandina kêmtir).',
    de: 'Empfindlichkeit bei der Anwendung (höher = weniger Änderungen).',
    es: 'Sensibilidad al aplicar el tratamiento (alta = menos cambios).',
    ru: 'Чувствительность при обработке (выше = меньше изменений).',
    fr: 'Sensibilité lors du traitement (plus élevé = moins de modifications).',
    it: "Sensibilità nell'applicazione (più alta = meno modifiche).",
  },

  // ===== Encoding step =====
  encodingSubtitle: {
    en: 'Transform categorical variables',
    tr: 'Kategorik değişkenleri dönüştür',
    ku: 'Guherbarên kategorîk biguherîne',
    de: 'Kategoriale Variablen transformieren',
    es: 'Transforma variables categóricas',
    ru: 'Преобразование категориальных признаков',
    fr: 'Transformer les variables catégorielles',
    it: 'Trasforma variabili categoriali',
  },
  encodingGlobalSettings: {
    en: 'Global Settings (Apply to All)',
    tr: 'Genel Ayarlar (Tümüne Uygula)',
    ku: 'Mîhengên Giştî (Ji hemûyan re)',
    de: 'Globale Einstellungen (auf alle anwenden)',
    es: 'Ajustes globales (aplicar a todo)',
    ru: 'Глобальные настройки (применить ко всем)',
    fr: 'Paramètres globaux (appliquer à tout)',
    it: 'Impostazioni globali (applica a tutto)',
  },
  defaultEncodingStrategy: {
    en: 'Default Encoding Strategy',
    tr: 'Varsayılan Kodlama Stratejisi',
    ku: 'Stratejiya kodkirinê ya standard',
    de: 'Standard-Codierstrategie',
    es: 'Estrategia de codificación por defecto',
    ru: 'Стратегия кодирования по умолчанию',
    fr: "Stratégie d'encodage par défaut",
    it: 'Strategia di codifica predefinita',
  },
  maxCategoriesAuto: {
    en: 'Max Categories (Auto)',
    tr: 'Maksimum Kategori (Otomatik)',
    ku: 'Kategoriyên Zêdetirîn (Auto)',
    de: 'Max. Kategorien (Auto)',
    es: 'Máx. categorías (Auto)',
    ru: 'Макс. категорий (Авто)',
    fr: 'Nb max de catégories (Auto)',
    it: 'Categorie massime (Auto)',
  },
  targetColumn: {
    en: 'Target Column',
    tr: 'Hedef Sütun',
    ku: 'Stûna Hedef',
    de: 'Zielspalte',
    es: 'Columna objetivo',
    ru: 'Целевая колонка',
    fr: 'Colonne cible',
    it: 'Colonna target',
  },
  applyGlobalSettings: {
    en: 'Apply Global Settings',
    tr: 'Genel Ayarları Uygula',
    ku: 'Mîhengên giştî bisebindin',
    de: 'Globale Einstellungen anwenden',
    es: 'Aplicar ajustes globales',
    ru: 'Применить глобальные настройки',
    fr: 'Appliquer les paramètres globaux',
    it: 'Applica impostazioni globali',
  },
  columnSpecificSettingsTitle: {
    en: 'Column-Specific Settings',
    tr: 'Sütuna Özel Ayarlar',
    ku: 'Mîhengên taybet bi stûnê',
    de: 'Spaltenspezifische Einstellungen',
    es: 'Ajustes por columna',
    ru: 'Настройки для отдельных столбцов',
    fr: 'Paramètres par colonne',
    it: 'Impostazioni per colonna',
  },
  addColumnBtn: {
    en: 'Add Column',
    tr: 'Sütun Ekle',
    ku: 'Stûn zêde bike',
    de: 'Spalte hinzufügen',
    es: 'Añadir columna',
    ru: 'Добавить столбец',
    fr: 'Ajouter une colonne',
    it: 'Aggiungi colonna',
  },
  noColumnsYet: {
    en: 'No columns added yet.',
    tr: 'Henüz sütun eklemediniz.',
    ku: 'Hêç stûn nehate zêdekirin.',
    de: 'Noch keine Spalten hinzugefügt.',
    es: 'Aún no has añadido columnas.',
    ru: 'Столбцы ещё не добавлены.',
    fr: 'Aucune colonne ajoutée pour le moment.',
    it: 'Nessuna colonna aggiunta.',
  },
  strategyLabel: { en: 'Strategy', tr: 'Strateji', ku: 'Stratejî', de: 'Strategie', es: 'Estrategia', ru: 'Стратегия', fr: 'Stratégie', it: 'Strategia' },
  treatUnknownAsMinusOne: {
    en: 'Treat unknowns as -1',
    tr: 'Bilinmeyenleri -1 olarak kabul et',
    ku: 'Nenasan wek -1 bibîne',
    de: 'Unbekannte als -1 behandeln',
    es: 'Tratar desconocidos como -1',
    ru: 'Считать неизвестные как -1',
    fr: 'Traiter les inconnus comme -1',
    it: 'Considera gli sconosciuti come -1',
  },
  applyColumnSettings: {
    en: 'Apply Column Settings',
    tr: 'Sütun Ayarlarını Uygula',
    ku: 'Mîhengên stûnê bisebindin',
    de: 'Spalteneinstellungen anwenden',
    es: 'Aplicar ajustes por columna',
    ru: 'Применить настройки столбцов',
    fr: 'Appliquer paramètres par colonne',
    it: 'Applica impostazioni colonne',
  },
  continueToNextStep: {
    en: 'Continue to Next Step',
    tr: 'Sonraki Adıma Devam Et',
    ku: 'Berdewamke bo gavê pêş',
    de: 'Weiter zum nächsten Schritt',
    es: 'Continuar al siguiente paso',
    ru: 'Перейти к следующему шагу',
    fr: "Passer à l'étape suivante",
    it: 'Continua al passo successivo',
  },
  selectPlaceholder: {
    en: 'Select…',
    tr: 'Seçiniz…',
    ku: 'Hilbijêrin…',
    de: 'Auswählen…',
    es: 'Seleccionar…',
    ru: 'Выберите…',
    fr: 'Sélectionner…',
    it: 'Seleziona…',
  },
  applying: {
    en: 'Applying…',
    tr: 'Uygulanıyor…',
    ku: 'Tê sepanîn…',
    de: 'Wird angewendet…',
    es: 'Aplicando…',
    ru: 'Применяется…',
    fr: 'Application…',
    it: 'Applicazione…',
  },
  infoEncodingGlobal: {
    en: 'Default encoding policy used for all eligible columns unless overridden below.',
    tr: 'Aşağıda geçersiz kılınmadıkça tüm uygun sütunlara uygulanacak varsayılan kodlama politikası.',
    ku: 'Heke li jêr nehate derbas kirin, bo hemû stûnên derbasbar siyaseta kodkirinê ya standard.',
    de: 'Standard-Codierregel für alle geeigneten Spalten, sofern unten nicht überschrieben.',
    es: 'Política de codificación por defecto para todas las columnas elegibles salvo anulación abajo.',
    ru: 'Стратегия кодирования по умолчанию для всех подходящих столбцов, если ниже не переопределена.',
    fr: 'Politique d’encodage par défaut pour toutes les colonnes éligibles sauf override ci-dessous.',
    it: 'Politica di codifica predefinita per tutte le colonne idonee salvo override sotto.',
  },
  infoDefaultEncodingStrategy: {
    en: 'Choose how categoricals are encoded by default (Auto, Label, One-Hot, Ordinal, Binary, Target).',
    tr: 'Kategorik değişkenlerin varsayılan olarak nasıl kodlanacağını seçin (Auto, Label, One-Hot, Ordinal, Binary, Target).',
    ku: 'Hilbijêre ka kategorîk çawa bi pêşdanasî têne kodkirin.',
    de: 'Wählen Sie die Standard-Codierung für Kategoriale (Auto, Label, One-Hot, Ordinal, Binary, Target).',
    es: 'Elige la codificación por defecto de categóricas (Auto, Label, One-Hot, Ordinal, Binary, Target).',
    ru: 'Выберите способ кодирования категориальных признаков по умолчанию.',
    fr: 'Choisissez l’encodage par défaut des catégorielles.',
    it: 'Scegli la codifica predefinita delle categoriali.',
  },
  infoMaxCategories: {
    en: 'Upper bound on unique categories considered by Auto before switching strategy.',
    tr: 'Auto stratejisi başka yönteme geçmeden önce dikkate alacağı benzersiz kategori üst sınırı.',
    ku: 'Sînorê jorcinsaziyê ya kategoriyên yekta ji bo “Auto” berî guherandinê.',
    de: 'Obergrenze der eindeutigen Kategorien für Auto, bevor die Strategie wechselt.',
    es: 'Límite de categorías únicas considerado por Auto antes de cambiar de estrategia.',
    ru: 'Верхняя граница уникальных категорий для Auto до смены стратегии.',
    fr: 'Plafond des catégories uniques prises par Auto avant de changer de stratégie.',
    it: 'Limite superiore di categorie uniche usate da Auto prima di cambiare strategia.',
  },
  infoEncodingTarget: {
    en: 'Column used as target when applying target encoding.',
    tr: 'Target encoding uygulanırken kullanılacak hedef sütun.',
    ku: 'Stûna hedef ya ji bo target encodingê.',
    de: 'Spalte, die beim Target Encoding als Ziel verwendet wird.',
    es: 'Columna usada como objetivo en target encoding.',
    ru: 'Столбец-цель для target encoding.',
    fr: 'Colonne cible pour le target encoding.',
    it: 'Colonna target per il target encoding.',
  },
  infoEncodingColumnSpecific: {
    en: 'Override the global policy with per-column strategies.',
    tr: 'Genel politikayı sütuna özel stratejilerle geçersiz kılın.',
    ku: 'Siyaseta giştî bi stratejiyên stûnê biguherîne.',
    de: 'Globale Richtlinie mit spaltenspezifischen Strategien überschreiben.',
    es: 'Anula la política global con estrategias por columna.',
    ru: 'Переопределите глобальную политику стратегиями по столбцам.',
    fr: 'Outrepassez la politique globale avec des stratégies par colonne.',
    it: 'Sostituisci la politica globale con strategie per colonna.',
  },
  infoEncodingStrategyPerColumn: {
    en: 'Select an encoding method for this column only.',
    tr: 'Yalnızca bu sütun için bir kodlama yöntemi seçin.',
    ku: 'Tenê ji bo vê stûnê rêbaza kodkirinê hilbijêre.',
    de: 'Wählen Sie eine Codierung nur für diese Spalte.',
    es: 'Selecciona un método de codificación para esta columna.',
    ru: 'Выберите метод кодирования только для этого столбца.',
    fr: 'Choisissez une méthode d’encodage pour cette colonne.',
    it: 'Seleziona un metodo di codifica per questa colonna.',
  },
  infoOrdinalUnknowns: {
    en: 'When checked, unseen categories are encoded as −1.',
    tr: 'İşaretlendiğinde, görülmeyen kategoriler −1 olarak kodlanır.',
    ku: 'Dema hatî nîşankirin, kategoriyên nenîhatî −1 tên kodkirin.',
    de: 'Wenn aktiviert, werden unbekannte Kategorien als −1 codiert.',
    es: 'Si está activado, las categorías no vistas se codifican como −1.',
    ru: 'Если включено, невиданные категории кодируются как −1.',
    fr: 'Si coché, les catégories inconnues sont encodées à −1.',
    it: 'Se attivo, le categorie non viste sono codificate a −1.',
  },
  noAvailableColumns: {
    en: 'No available column to add.',
    tr: 'Eklenecek uygun sütun kalmadı.',
    ku: 'Hêç stûnê amade nayê zêdekirin.',
    de: 'Keine verfügbare Spalte zum Hinzufügen.',
    es: 'No hay columnas disponibles para añadir.',
    ru: 'Нет доступных столбцов для добавления.',
    fr: 'Aucune colonne disponible à ajouter.',
    it: 'Nessuna colonna disponibile da aggiungere.',
  },
  pleaseSelectTarget: {
    en: 'Please select a target column for Target strategy.',
    tr: 'Target stratejisi için lütfen bir hedef sütun seçin.',
    ku: 'Ji bo stratejiyê Target ji kerema xwe stûna hedef hilbijêrin.',
    de: 'Bitte eine Zielspalte für die Target-Strategie auswählen.',
    es: 'Selecciona una columna objetivo para la estrategia Target.',
    ru: 'Выберите целевой столбец для стратегии Target.',
    fr: 'Veuillez sélectionner une colonne cible pour la stratégie Target.',
    it: 'Seleziona una colonna target per la strategia Target.',
  },
  globalEncodingApplied: {
    en: 'Global encoding applied.',
    tr: 'Global encoding uygulandı.',
    ku: 'Kodkirina giştî hate sepandin.',
    de: 'Globale Codierung angewendet.',
    es: 'Codificación global aplicada.',
    ru: 'Глобальное кодирование применено.',
    fr: 'Encodage global appliqué.',
    it: 'Codifica globale applicata.',
  },
  globalEncodingFailed: {
    en: 'Global encoding failed.',
    tr: 'Global encoding başarısız.',
    ku: 'Kodkirina giştî sernebû.',
    de: 'Globale Codierung fehlgeschlagen.',
    es: 'Error en la codificación global.',
    ru: 'Сбой глобального кодирования.',
    fr: "Échec de l'encodage global.",
    it: 'Codifica globale non riuscita.',
  },
  pleaseAddColumnFirst: {
    en: 'Add a column first.',
    tr: 'Önce sütun ekleyin.',
    ku: 'Pêşî stûnê zêde bike.',
    de: 'Fügen Sie zuerst eine Spalte hinzu.',
    es: 'Agrega primero una columna.',
    ru: 'Сначала добавьте столбец.',
    fr: "Ajoutez d'abord une colonne.",
    it: 'Aggiungi prima una colonna.',
  },
  pleaseSelectTargetForColumn: {
    en: 'Target strategy selected for a column. Please set a Target Column above.',
    tr: 'Bir sütun için Target seçtiniz. Lütfen yukarıdan bir Hedef Sütun belirleyin.',
    ku: 'Ji bo stûnê Target hatiye hilbijartin. Ji jorê Stûna Hedef mîheng bike.',
    de: 'Target-Strategie für eine Spalte gewählt. Bitte oben eine Zielspalte setzen.',
    es: 'Elegiste Target para una columna. Define la Columna Objetivo arriba.',
    ru: 'Для столбца выбрана Target-стратегия. Укажите целевой столбец выше.',
    fr: 'Stratégie Target choisie pour une colonne. Définissez la colonne cible ci-dessus.',
    it: 'Target selezionata per una colonna. Imposta una Colonna Target sopra.',
  },
  columnEncodingApplied: {
    en: 'Column-specific encoding applied.',
    tr: 'Sütun bazlı encoding uygulandı.',
    ku: 'Kodkirina taybet bi stûnê hate sepandin.',
    de: 'Spaltenspezifische Codierung angewendet.',
    es: 'Codificación por columna aplicada.',
    ru: 'Кодирование для столбцов применено.',
    fr: "Encodage par colonne appliqué.",
    it: 'Codifica per colonna applicata.',
  },
  columnEncodingFailed: {
    en: 'Column-specific encoding failed.',
    tr: 'Sütun bazlı encoding başarısız.',
    ku: 'Kodkirina taybet bi stûnê sernebû.',
    de: 'Spaltenspezifische Codierung fehlgeschlagen.',
    es: 'Error en la codificación por columna.',
    ru: 'Сбой кодирования по столбцам.',
    fr: "Échec de l'encodage par colonne.",
    it: 'Codifica per colonna non riuscita.',
  },

  // ===== Correlation step =====
  correlationAnalysis: {
    en: 'Correlation Analysis',
    tr: 'Korelasyon Analizi',
    ku: 'Analîza Têkilî',
    de: 'Korrelationsanalyse',
    es: 'Análisis de correlación',
    ru: 'Анализ корреляций',
    fr: 'Analyse de corrélation',
    it: 'Analisi di correlazione',
  },
  correlationSubtitle: {
    en: 'Reduce multicollinearity by removing highly correlated features. For each pair, select the one to DROP.',
    tr: 'Yüksek korelasyonlu özellikleri kaldırarak çoklu doğrusal bağıntıyı azaltın. Her çift için KALDIRILACAK olanı seçin.',
    ku: 'Bi rakirina taybetmendiyên bi têkilîya bilind, multi-kolinearîtê kêm bike. Ji her du-parê, ya bê wergerînê hilbijêre.',
    de: 'Reduzieren Sie Multikollinearität, indem Sie hoch korrelierte Merkmale entfernen. Wählen Sie pro Paar die zu LÖSCHENDE Spalte.',
    es: 'Reduce la multicolinealidad eliminando variables altamente correlacionadas. En cada par, elige cuál ELIMINAR.',
    ru: 'Снизьте мультиколлинеарность, удаляя сильно коррелированные признаки. В каждой паре выберите признак для УДАЛЕНИЯ.',
    fr: 'Réduisez la multicolinéarité en supprimant les variables fortement corrélées. Pour chaque paire, choisissez celle à SUPPRIMER.',
    it: 'Riduci la multicollinearità rimuovendo le feature altamente correlate. Per ogni coppia, scegli quella da ELIMINARE.',
  },
  correlationSettings: {
    en: 'Correlation Settings',
    tr: 'Korelasyon Ayarları',
    ku: 'Mîhengên Têkilî',
    de: 'Korrelationseinstellungen',
    es: 'Ajustes de correlación',
    ru: 'Настройки корреляции',
    fr: 'Paramètres de corrélation',
    it: 'Impostazioni di correlazione',
  },
  correlationThreshold: {
    en: 'Correlation Threshold',
    tr: 'Korelasyon Eşiği',
    ku: 'Astenga Têkilî',
    de: 'Korrelationsschwelle',
    es: 'Umbral de correlación',
    ru: 'Порог корреляции',
    fr: 'Seuil de corrélation',
    it: 'Soglia di correlazione',
  },
  pairsListedHint: {
    en: 'Pairs with |correlation| ≥ threshold are listed.',
    tr: 'Mutlak korelasyonu eşiğe ≥ olan çiftler listelenir.',
    ku: 'Du-parên bi |têkilî| ≥ astengê tên nîşandan.',
    de: 'Paare mit |Korrelation| ≥ Schwelle werden gelistet.',
    es: 'Se listan los pares con |correlación| ≥ umbral.',
    ru: 'Отображаются пары с |корреляцией| ≥ порога.',
    fr: 'Les paires avec |corrélation| ≥ au seuil sont listées.',
    it: 'Sono elencate le coppie con |correlazione| ≥ soglia.',
  },
  highlyCorrelatedPairs: {
    en: 'Highly Correlated Pairs',
    tr: 'Yüksek Korelasyonlu Çiftler',
    ku: 'Du-parên bi têkilîya bilind',
    de: 'Hoch korrelierte Paare',
    es: 'Pares altamente correlacionados',
    ru: 'Пары с высокой корреляцией',
    fr: 'Paires fortement corrélées',
    it: 'Coppie altamente correlate',
  },
  highlyCorrelatedFeaturesTitle: {
    en: 'Highly Correlated Features (select the one to drop in each pair)',
    tr: 'Yüksek Korelasyonlu Özellikler (her çiftte kaldırılacak olanı seçin)',
    ku: 'Taybetmendiyên bi têkilîya bilind (li her du-parê ya wergerînê hilbijêre)',
    de: 'Stark korrelierte Merkmale (pro Paar eines zum Löschen wählen)',
    es: 'Variables altamente correlacionadas (elige cuál eliminar en cada par)',
    ru: 'Сильно коррелирующие признаки (в каждой паре выберите один для удаления)',
    fr: 'Caractéristiques fortement corrélées (choisir celle à supprimer par paire)',
    it: 'Feature altamente correlate (scegli quale eliminare per ogni coppia)',
  },
  correlationLabel: { en: 'Correlation:', tr: 'Korelasyon:', ku: 'Têkilî:', de: 'Korrelation:', es: 'Correlación:', ru: 'Корреляция:', fr: 'Corrélation :', it: 'Correlazione:' },
  columnsToDrop: {
    en: 'Columns to drop',
    tr: 'Kaldırılacak sütunlar',
    ku: 'Stûnên wê werin rakirin',
    de: 'Zu löschende Spalten',
    es: 'Columnas a eliminar',
    ru: 'Столбцы к удалению',
    fr: 'Colonnes à supprimer',
    it: 'Colonne da rimuovere',
  },
  noHighlyCorrelated: {
    en: 'No highly correlated features found',
    tr: 'Yüksek korelasyonlu özellik bulunmadı',
    ku: 'Taybetmendiyên bi têkilîya bilind nehat dîtin',
    de: 'Keine stark korrelierten Merkmale gefunden',
    es: 'No se encontraron variables altamente correlacionadas',
    ru: 'Сильно коррелирующие признаки не найдены',
    fr: 'Aucune variable fortement corrélée trouvée',
    it: 'Nessuna feature altamente correlata trovata',
  },
  allBelowThreshold: {
    en: 'All feature correlations are below the current threshold.',
    tr: 'Tüm özellik korelasyonları mevcut eşiğin altında.',
    ku: 'Hemû têkilîyên taybetmendiyan jêr astengê heyî ne.',
    de: 'Alle Merkmalskorrelationen liegen unter der aktuellen Schwelle.',
    es: 'Todas las correlaciones están por debajo del umbral actual.',
    ru: 'Все корреляции признаков ниже текущего порога.',
    fr: 'Toutes les corrélations sont sous le seuil actuel.',
    it: 'Tutte le correlazioni sono sotto la soglia corrente.',
  },
  applyAndDrop: {
    en: 'Apply & Drop',
    tr: 'Uygula ve Kaldır',
    ku: 'Bikaranîn û Rake',
    de: 'Anwenden & Löschen',
    es: 'Aplicar y eliminar',
    ru: 'Применить и удалить',
    fr: 'Appliquer & supprimer',
    it: 'Applica e rimuovi',
  },
  processing: {
    en: 'Processing…',
    tr: 'İşleniyor…',
    ku: 'Tê xebitandin…',
    de: 'Verarbeite…',
    es: 'Procesando…',
    ru: 'Обработка…',
    fr: 'Traitement…',
    it: 'Elaborazione…',
  },
  drop: { en: 'Drop', tr: 'Kaldır', ku: 'Rake', de: 'Löschen', es: 'Eliminar', ru: 'Удалить', fr: 'Supprimer', it: 'Rimuovi' },
  pleaseSelectColumnsToDrop: {
    en: 'Please select at least one column to drop.',
    tr: 'Lütfen kaldırmak için en az bir sütun seçin.',
    ku: 'Ji kerema xwe bi kêmanî yek stûnê ji bo rakirinê hilbijêre.',
    de: 'Bitte wählen Sie mindestens eine zu löschende Spalte aus.',
    es: 'Selecciona al menos una columna para eliminar.',
    ru: 'Выберите хотя бы один столбец для удаления.',
    fr: 'Veuillez sélectionner au moins une colonne à supprimer.',
    it: 'Seleziona almeno una colonna da rimuovere.',
  },
  columnsDropped: {
    en: 'columns dropped',
    tr: 'sütun kaldırıldı',
    ku: 'stûn hate rakirin',
    de: 'Spalten gelöscht',
    es: 'columnas eliminadas',
    ru: 'столбцов удалено',
    fr: 'colonnes supprimées',
    it: 'colonne rimosse',
  },
  applyError: {
    en: 'An error occurred while applying.',
    tr: 'Uygulama sırasında bir hata oluştu.',
    ku: 'Di dema sepandinê de çewtîek çêbû.',
    de: 'Beim Anwenden ist ein Fehler aufgetreten.',
    es: 'Se produjo un error al aplicar.',
    ru: 'Произошла ошибка при применении.',
    fr: "Une erreur est survenue lors de l'application.",
    it: "Si è verificato un errore durante l’applicazione.",
  },
  infoCorrelationThreshold: {
    en: 'Absolute Pearson correlation in [0–1]. Pairs with |corr| ≥ threshold are treated as highly correlated.',
    tr: 'Mutlak Pearson korelasyonu [0–1]. |corr| ≥ eşik olan çiftler yüksek korelasyonlu sayılır.',
    ku: 'Têkilîya Pearson a tevahî di [0–1] de. Du-parên bi |corr| ≥ astengê têne wateya bilind.',
    de: 'Absolute Pearson-Korrelation in [0–1]. Paare mit |corr| ≥ Schwelle gelten als hoch korreliert.',
    es: 'Correlación de Pearson absoluta en [0–1]. Pares con |corr| ≥ umbral se consideran altamente correlacionados.',
    ru: 'Абсолютная корреляция Пирсона в [0–1]. Пары с |corr| ≥ порога считаются высоко коррелированными.',
    fr: 'Corrélation de Pearson absolue dans [0–1]. Paires avec |corr| ≥ seuil considérées comme fortement corrélées.',
    it: 'Correlazione di Pearson assoluta in [0–1]. Coppie con |corr| ≥ soglia sono altamente correlate.',
  },
  infoCorrelationPairsCount: {
    en: 'Number of pairs detected as highly correlated at the current threshold.',
    tr: 'Geçerli eşikte yüksek korelasyonlu olarak tespit edilen çift sayısı.',
    ku: 'Hejmara du-parên ku di astengê heyî de bi têkilîya bilind hatine dîtin.',
    de: 'Anzahl der bei aktueller Schwelle erkannten hoch korrelierten Paare.',
    es: 'Número de pares detectados como altamente correlacionados al umbral actual.',
    ru: 'Количество пар, признанных высоко коррелированными при текущем пороге.',
    fr: 'Nombre de paires détectées comme fortement corrélées au seuil actuel.',
    it: 'Numero di coppie rilevate come altamente correlate alla soglia attuale.',
  },
  infoCorrelationPairsList: {
    en: 'For each pair above the threshold, choose one feature to drop.',
    tr: 'Eşiğin üzerindeki her çift için kaldırılacak bir özelliği seçin.',
    ku: 'Ji bo her du-parê li jorê astengê, taybetmendiyek ji bo rakirinê hilbijêre.',
    de: 'Für jedes Paar über der Schwelle wählen Sie ein zu löschendes Merkmal.',
    es: 'Para cada par por encima del umbral, elige una variable a eliminar.',
    ru: 'Для каждой пары выше порога выберите один признак для удаления.',
    fr: 'Pour chaque paire au-dessus du seuil, choisissez une variable à supprimer.',
    it: 'Per ogni coppia sopra la soglia, scegli una feature da rimuovere.',
  },

  // ===== Scaling step (tooltips) =====
  infoScalingOverview: {
    en: 'Normalize numeric features to comparable scales; improves convergence and distance-based models.',
    tr: 'Sayısal özellikleri ortak ölçeklere getirir; yakınsama ve mesafe-tabanlı modelleri iyileştirir.',
    ku: 'Taybetmendiyên hejmarî li pîvangehek hevpar têne anîn; yekgirtina fêr bûnê û modelên li ser dûrîyê baş dike.',
    de: 'Bringt numerische Merkmale auf vergleichbare Skalen; verbessert Konvergenz und Distanz-basierte Modelle.',
    es: 'Normaliza rasgos numéricos a escalas comparables; mejora la convergencia y los modelos basados en distancia.',
    ru: 'Приводит числовые признаки к сопоставимым шкалам; улучшает сходимость и методы на расстояниях.',
    fr: 'Normalise les variables numériques sur des échelles comparables ; améliore la convergence et les modèles à distance.',
    it: 'Normalizza le variabili numeriche su scale comparabili; migliora la convergenza e i modelli basati sulla distanza.',
  },
  infoGlobalScaling: {
    en: 'Default scaling applied to all numeric columns unless overridden or excluded as target.',
    tr: 'Aşağıda özelleştirilmedikçe ve hedef olarak hariç tutulmadıkça tüm sayısal sütunlara uygulanır.',
    ku: 'Heke neyê guherandin an wek armanc nehate hilbijartin, li hemû stûnên hejmarî tê sepandin.',
    de: 'Standard-Skalierung für alle numerischen Spalten, sofern nicht überschrieben oder als Ziel ausgeschlossen.',
    es: 'Escalado por defecto en todas las columnas numéricas salvo override o exclusión como objetivo.',
    ru: 'Масштабирование по умолчанию для всех числовых столбцов, если не переопределено или не исключено как целевой.',
    fr: "Mise à l'échelle par défaut sur toutes les colonnes numériques, sauf override ou exclusion comme cible.",
    it: 'Scalatura predefinita su tutte le colonne numeriche salvo override o esclusione come target.',
  },
  infoDefaultScalingMethod: {
    en: 'Standard: (x−μ)/σ; Min-Max: to [0,1]; Robust: uses median/IQR for outlier resistance.',
    tr: 'Standard: (x−μ)/σ; Min-Max: [0,1]; Robust: aykırılara dayanıklı (median/IQR).',
    ku: 'Standard: (x−μ)/σ; Min-Max: [0,1]; Robust: bi navîn û IQR dijî outlieran.',
    de: 'Standard: (x−μ)/σ; Min-Max: auf [0,1]; Robust: Median/IQR für Ausreißerrobustheit.',
    es: 'Estándar: (x−μ)/σ; Min-Max: a [0,1]; Robusta: mediana/IQR para resistencia a outliers.',
    ru: 'Стандарт: (x−μ)/σ; Min-Max: в [0,1]; Робастная: медиана/IQR для устойчивости к выбросам.',
    fr: 'Standard : (x−μ)/σ ; Min-Max : vers [0,1] ; Robuste : médiane/IQR, résistant aux outliers.',
    it: 'Standard: (x−μ)/σ; Min-Max: in [0,1]; Robust: mediana/IQR resistente ai valori anomali.',
  },
  infoTargetSkipScaling: {
    en: 'Select a column to exclude from scaling (kept unchanged).',
    tr: 'Ölçeklemeden hariç tutulacak sütunu seçin (değişmeden kalır).',
    ku: 'Stûnekî hilbijêre ku ji pîvandina pîvandanê bê derxistin (wekî ku ye maye).',
    de: 'Spalte auswählen, die von der Skalierung ausgenommen wird (unverändert).',
    es: 'Seleccione una columna para excluir del escalado (se mantiene igual).',
    ru: 'Выберите столбец, который не нужно масштабировать (останется без изменений).',
    fr: 'Choisissez une colonne à exclure de la mise à l’échelle (inchangée).',
    it: 'Seleziona una colonna da escludere dallo scaling (rimane invariata).',
  },
  infoScalingColumnSpecific: {
    en: 'Override the global method for selected columns.',
    tr: 'Seçili sütunlar için global yöntemi geçersiz kılın.',
    ku: 'Ji bo stûnên hilbijartî rêbaza giştî biguherîne.',
    de: 'Globale Methode für ausgewählte Spalten überschreiben.',
    es: 'Anule el método global para columnas seleccionadas.',
    ru: 'Переопределите глобальный метод для выбранных столбцов.',
    fr: 'Outrepassez la méthode globale pour certaines colonnes.',
    it: 'Sovrascrivi il metodo globale per le colonne selezionate.',
  },

  // ===== Evaluation step (titles, labels, toasts, tooltips) =====
  resultsLabel: {
    en: 'Results',
    tr: 'Sonuçlar',
    ku: 'Encam',
    de: 'Ergebnisse',
    es: 'Resultados',
    ru: 'Результаты',
    fr: 'Résultats',
    it: 'Risultati',
  },
  evaluationSubtitle: {
    en: 'Analyze model performance metrics',
    tr: 'Model performans metriklerini analiz edin',
    ku: 'Metrîkên performansa modelan şîrove bike',
    de: 'Analysieren Sie die Leistungsmetriken der Modelle',
    es: 'Analiza las métricas de rendimiento del modelo',
    ru: 'Анализируйте метрики качества моделей',
    fr: 'Analysez les métriques de performance du modèle',
    it: 'Analizza le metriche di prestazione dei modelli',
  },
  evaluationSummary: {
    en: 'Evaluation Summary',
    tr: 'Değerlendirme Özeti',
    ku: 'Kurteya Nirxandinê',
    de: 'Auswertungsübersicht',
    es: 'Resumen de evaluación',
    ru: 'Итоги оценки',
    fr: "Résumé de l'évaluation",
    it: 'Riepilogo valutazione',
  },
  modelsTrained: {
    en: 'Models Trained',
    tr: 'Eğitilen Modeller',
    ku: 'Modelên xwendî',
    de: 'Trainierte Modelle',
    es: 'Modelos entrenados',
    ru: 'Обучено моделей',
    fr: 'Modèles entraînés',
    it: 'Modelli addestrati',
  },
  bestModel: {
    en: 'Best Model',
    tr: 'En İyi Model',
    ku: 'Modela herî baş',
    de: 'Bestes Modell',
    es: 'Mejor modelo',
    ru: 'Лучшая модель',
    fr: 'Meilleur modèle',
    it: 'Miglior modello',
  },
  problemTypeLabel: {
    en: 'Problem Type',
    tr: 'Problem Türü',
    ku: 'Tîpa Pirsgirêkê',
    de: 'Problemtyp',
    es: 'Tipo de problema',
    ru: 'Тип задачи',
    fr: 'Type de problème',
    it: 'Tipo di problema',
  },
  modelPerformanceComparison: {
    en: 'Model Performance Comparison',
    tr: 'Model Performans Karşılaştırması',
    ku: 'Berhevoka performansa modelan',
    de: 'Modellleistungsvergleich',
    es: 'Comparación de rendimiento de modelos',
    ru: 'Сравнение качества моделей',
    fr: 'Comparaison des performances des modèles',
    it: 'Confronto prestazioni modelli',
  },
  primaryMetric: {
    en: 'Primary metric',
    tr: 'Birincil metrik',
    ku: 'Metrîka sereke',
    de: 'Hauptmetrik',
    es: 'Métrica principal',
    ru: 'Основная метрика',
    fr: 'Métrique principale',
    it: 'Metrica primaria',
  },
  detailedMetrics: {
    en: 'Detailed Metrics',
    tr: 'Ayrıntılı Metrikler',
    ku: 'Metrîkên berfireh',
    de: 'Detaillierte Metriken',
    es: 'Métricas detalladas',
    ru: 'Подробные метрики',
    fr: 'Métriques détaillées',
    it: 'Metriche dettagliate',
  },
  exportModel: {
    en: 'Export Model',
    tr: 'Modeli Dışa Aktar',
    ku: 'Modelê derxe',
    de: 'Modell exportieren',
    es: 'Exportar modelo',
    ru: 'Экспорт модели',
    fr: 'Exporter le modèle',
    it: 'Esporta modello',
  },
  bestPerformingModel: {
    en: 'Best Performing Model',
    tr: 'En İyi Performans Gösteren Model',
    ku: 'Modela bi performansa herî baş',
    de: 'Leistungsstärkstes Modell',
    es: 'Modelo con mejor rendimiento',
    ru: 'Модель с лучшим качеством',
    fr: 'Modèle le plus performant',
    it: 'Modello con prestazioni migliori',
  },
  gotIt: { en: 'Got it', tr: 'Anladım', ku: 'Hîs kirim', de: 'Verstanden', es: 'Entendido', ru: 'Понятно', fr: 'Compris', it: 'Fatto' },

  // Evaluation toasts/messages
  evaluationCompleted: {
    en: 'Model evaluation completed',
    tr: 'Model değerlendirmesi tamamlandı',
    ku: 'Nirxandina modelê qediya',
    de: 'Modellbewertung abgeschlossen',
    es: 'Evaluación del modelo completada',
    ru: 'Оценка моделей завершена',
    fr: 'Évaluation du modèle terminée',
    it: 'Valutazione del modello completata',
  },
  evaluationFailed: {
    en: 'Failed to evaluate models',
    tr: 'Modeller değerlendirilirken hata oluştu',
    ku: 'Nikarî hûn modelan nirxandin',
    de: 'Bewertung der Modelle fehlgeschlagen',
    es: 'Error al evaluar los modelos',
    ru: 'Не удалось оценить модели',
    fr: "Échec de l'évaluation des modèles",
    it: 'Impossibile valutare i modelli',
  },
  pleaseSelectModel: {
    en: 'Select a model please.',
    tr: 'Lütfen bir model seçin.',
    ku: 'Ji kerema xwe modelek hilbijêre.',
    de: 'Bitte ein Modell auswählen.',
    es: 'Selecciona un modelo.',
    ru: 'Пожалуйста, выберите модель.',
    fr: 'Veuillez sélectionner un modèle.',
    it: 'Seleziona un modello.',
  },
  exportFailedEmpty: {
    en: 'Export failed: empty response.',
    tr: 'Dışa aktarma başarısız: boş yanıt.',
    ku: 'Derxistin biserneket: bersiva vala.',
    de: 'Export fehlgeschlagen: leere Antwort.',
    es: 'Exportación fallida: respuesta vacía.',
    ru: 'Экспорт не выполнен: пустой ответ.',
    fr: 'Échec de l’export : réponse vide.',
    it: 'Esportazione non riuscita: risposta vuota.',
  },
  modelDownloaded: {
    en: 'Model downloaded.',
    tr: 'Model indirildi.',
    ku: 'Model hate daxistin.',
    de: 'Modell heruntergeladen.',
    es: 'Modelo descargado.',
    ru: 'Модель скачана.',
    fr: 'Modèle téléchargé.',
    it: 'Modello scaricato.',
  },
  exportFailed: {
    en: 'Export failed.',
    tr: 'Dışa aktarma başarısız.',
    ku: 'Derxistin serneket.',
    de: 'Export fehlgeschlagen.',
    es: 'La exportación falló.',
    ru: 'Экспорт не удался.',
    fr: "Échec de l'export.",
    it: "Esportazione non riuscita.",
  },
  noTrainingResults: {
    en: 'No training results found. Please complete the training step first.',
    tr: 'Eğitim sonuçları bulunamadı. Lütfen önce eğitim adımını tamamlayın.',
    ku: 'Encamên perwerdehiyê nehatin dîtin. Ji kerema xwe gavê perwerdehiyê pêş bixebitînin.',
    de: 'Keine Trainingsergebnisse gefunden. Bitte schließen Sie zuerst den Trainingsschritt ab.',
    es: 'No se encontraron resultados de entrenamiento. Completa primero el paso de entrenamiento.',
    ru: 'Результаты обучения не найдены. Сначала завершите шаг обучения.',
    fr: "Aucun résultat d'entraînement trouvé. Veuillez d'abord terminer l'étape d'entraînement.",
    it: 'Nessun risultato di training trovato. Completa prima il training.',
  },
  evaluatingModels: {
    en: 'Evaluating models...',
    tr: 'Modeller değerlendiriliyor...',
    ku: 'Modelan têne nirxandin...',
    de: 'Bewerte Modelle...',
    es: 'Evaluando modelos...',
    ru: 'Оцениваем модели...',
    fr: 'Évaluation des modèles…',
    it: 'Valutazione dei modelli...',
  },

  // Evaluation tooltips (section-level)
  infoEvaluationOverview: {
    en: 'Compare models using key metrics. Hover any (i) to learn more.',
    tr: 'Modelleri temel metriklerle karşılaştırın. Daha fazlası için (i) simgesine gelin.',
    ku: 'Modelan bi metrîkên sereke re hevbigire. Ji bo hîn bêtir li (i) were.',
    de: 'Vergleichen Sie Modelle anhand zentraler Metriken. Fahren Sie über (i) für Details.',
    es: 'Compara modelos con métricas clave. Pasa sobre (i) para saber más.',
    ru: 'Сравнивайте модели по ключевым метрикам. Наведите на (i) для описания.',
    fr: 'Comparez les modèles via des métriques clés. Survolez (i) pour en savoir plus.',
    it: 'Confronta i modelli con metriche chiave. Passa su (i) per dettagli.',
  },
  infoEvaluationSummary: {
    en: 'A quick snapshot of trained models, best pick and detected problem type.',
    tr: 'Eğitilen modeller, en iyi seçim ve tespit edilen problem türüne hızlı bakış.',
    ku: 'Sûreta kin a modelên fêr bûyî, bijartina herî baş û tîpa pirsgirêkê.',
    de: 'Kurzüberblick: trainierte Modelle, beste Wahl und Problemtyp.',
    es: 'Instantánea de modelos entrenados, mejor opción y tipo de problema.',
    ru: 'Краткий обзор обученных моделей, лучшей и типа задачи.',
    fr: 'Aperçu des modèles entraînés, du meilleur choix et du type de problème.',
    it: 'Panoramica di modelli addestrati, migliore scelta e tipo di problema.',
  },
  infoModelsTrained: {
    en: 'Total number of models successfully evaluated.',
    tr: 'Başarıyla değerlendirilen model sayısı.',
    ku: 'Hemî hejmara modelên serketî hate nirxandin.',
    de: 'Anzahl der erfolgreich bewerteten Modelle.',
    es: 'Número total de modelos evaluados con éxito.',
    ru: 'Число успешно оценённых моделей.',
    fr: 'Nombre total de modèles évalués avec succès.',
    it: 'Numero totale di modelli valutati correttamente.',
  },
  infoBestModel: {
    en: 'Model with the best primary metric at this step.',
    tr: 'Bu adımda birincil metrikte en iyi sonucu veren model.',
    ku: 'Modelê ku li metrîka sereke herî baş ye.',
    de: 'Modell mit der besten Hauptmetrik in diesem Schritt.',
    es: 'Modelo con la mejor métrica primaria en este paso.',
    ru: 'Модель с лучшей основной метрикой на этом шаге.',
    fr: 'Modèle avec la meilleure métrique principale à cette étape.',
    it: 'Modello con la migliore metrica primaria in questa fase.',
  },
  infoProblemTypeEval: {
    en: 'Detected or selected learning task (classification, regression, clustering).',
    tr: 'Algılanan veya seçilen öğrenme görevi (sınıflandırma, regresyon, kümeleme).',
    ku: 'Peywirandina fêr bûnê ya hate nasîn an hilbijartin (class., regr., clustering).',
    de: 'Erkannte oder gewählte Lernaufgabe (Klassifikation, Regression, Clustering).',
    es: 'Tarea de aprendizaje detectada o seleccionada (clasificación, regresión, clustering).',
    ru: 'Определённая или выбранная задача (классификация, регрессия, кластеризация).',
    fr: 'Tâche d’apprentissage détectée ou choisie (classification, régression, clustering).',
    it: 'Compito rilevato o selezionato (classificazione, regressione, clustering).',
  },
  infoPerformanceChart: {
    en: 'Bar chart comparing the primary metric across trained models.',
    tr: 'Eğitilen modeller arasında birincil metriği karşılaştıran çubuk grafik.',
    ku: 'Grafîka darê ku metrîka sereke di navbera modelan de tê berhev kirin.',
    de: 'Balkendiagramm der Hauptmetrik über alle trainierten Modelle.',
    es: 'Gráfico de barras comparando la métrica principal entre modelos.',
    ru: 'Столбчатый график основной метрики по моделям.',
    fr: 'Histogramme comparant la métrique principale entre modèles.',
    it: 'Grafico a barre della metrica primaria tra i modelli.',
  },
  infoPrimaryMetric: {
    en: 'Main metric used to sort and select the best model for this problem type.',
    tr: 'Bu problem türü için en iyi modeli sıralayıp seçmekte kullanılan ana metrik.',
    ku: 'Metrîka sereke ji bo rêz kirin û hilbijartina modela herî baş.',
    de: 'Hauptmetrik zum Sortieren und Auswählen des besten Modells.',
    es: 'Métrica principal usada para ordenar y seleccionar el mejor modelo.',
    ru: 'Основная метрика для выбора лучшей модели.',
    fr: 'Métrique principale pour sélectionner le meilleur modèle.',
    it: 'Metrica principale per scegliere il miglior modello.',
  },
  infoDetailedMetrics: {
    en: 'All reported metrics per model. Colors: green ≈ good, yellow ≈ okay, red ≈ poor.',
    tr: 'Model başına tüm metrikler. Renkler: yeşil ≈ iyi, sarı ≈ orta, kırmızı ≈ zayıf.',
    ku: 'Hemû metrîkên ragihandî ji bo her modelê. Reng: kesk ≈ baş, zêr ≈ navîn, sor ≈ lawaz.',
    de: 'Alle Metriken pro Modell. Farben: grün ≈ gut, gelb ≈ ok, rot ≈ schwach.',
    es: 'Todas las métricas por modelo. Colores: verde ≈ bien, amarillo ≈ ok, rojo ≈ pobre.',
    ru: 'Все метрики по модели. Цвета: зелёный ≈ хорошо, жёлтый ≈ средне, красный ≈ плохо.',
    fr: 'Toutes les métriques par modèle. Couleurs : vert ≈ bon, jaune ≈ moyen, rouge ≈ faible.',
    it: 'Tutte le metriche per modello. Colori: verde ≈ buono, giallo ≈ ok, rosso ≈ scarso.',
  },
  infoRowModelMetrics: {
    en: 'Metrics computed for this specific model.',
    tr: 'Bu modele özel hesaplanan metrikler.',
    ku: 'Metrîkên ji bo vî modelê hate hesibandin.',
    de: 'Für dieses Modell berechnete Metriken.',
    es: 'Métricas calculadas para este modelo.',
    ru: 'Метрики, рассчитанные для данной модели.',
    fr: 'Métriques calculées pour ce modèle.',
    it: 'Metriche calcolate per questo modello.',
  },
  infoBestHighlight: {
    en: 'The model that performs best according to the primary metric.',
    tr: 'Birincil metriğe göre en iyi performansı gösteren model.',
    ku: 'Modelê ku li gorî metrîka sereke herî baş dixebite.',
    de: 'Modell mit der besten Leistung laut Hauptmetrik.',
    es: 'Modelo con mejor rendimiento según la métrica principal.',
    ru: 'Модель с лучшей основной метрикой.',
    fr: 'Le modèle le plus performant selon la métrique principale.',
    it: 'Il modello con la migliore metrica primaria.',
  },
  bestModelNarrative: {
    en: 'Based on the evaluation metrics, the selected model shows the best performance for this task. You can proceed to optimization or export the model.',
    tr: 'Değerlendirme metriklerine göre seçilen model bu görev için en iyi performansı gösteriyor. Optimizasyona devam edebilir veya modeli dışa aktarabilirsiniz.',
    ku: 'Li gorî metrîkên nirxandinê, ev model ji bo vî pêvajoiyê herî baş e. Dikarin berdewam bikî bo optimîzasyonê an modelê derxînî.',
    de: 'Basierend auf den Metriken zeigt das ausgewählte Modell die beste Leistung. Sie können mit der Optimierung fortfahren oder das Modell exportieren.',
    es: 'Según las métricas, el modelo seleccionado ofrece el mejor rendimiento. Continúa con la optimización o exporta el modelo.',
    ru: 'По метрикам выбранная модель показывает наилучшее качество. Можно перейти к оптимизации или экспортировать модель.',
    fr: 'Selon les métriques, le modèle sélectionné offre la meilleure performance. Poursuivez vers l’optimisation ou exportez le modèle.',
    it: 'In base alle metriche, il modello selezionato è il migliore. Puoi procedere all’ottimizzazione o esportare il modello.',
  },
  infoExportOverview: {
    en: 'Download the trained model artifact to use in your apps.',
    tr: 'Uygulamalarınızda kullanmak için eğitilmiş model çıktısını indirin.',
    ku: 'Ji bo bikaranîna di sepanên xwe de artefakta modelê daxîne.',
    de: 'Laden Sie das trainierte Modellartefakt herunter.',
    es: 'Descarga el artefacto del modelo entrenado.',
    ru: 'Скачайте артефакт обученной модели.',
    fr: 'Téléchargez l’artefact du modèle entraîné.',
    it: 'Scarica l’artefatto del modello addestrato.',
  },
  infoExportSelectModel: {
    en: 'Choose which trained model to export.',
    tr: 'Hangi eğitilmiş modeli dışa aktaracağınızı seçin.',
    ku: 'Hilbijêre kîjan modelê fêr bûyî derxînin.',
    de: 'Wählen Sie das zu exportierende Modell.',
    es: 'Elige qué modelo exportar.',
    ru: 'Выберите, какую модель экспортировать.',
    fr: 'Choisissez quel modèle exporter.',
    it: 'Scegli quale modello esportare.',
  },
  infoExportFormat: {
    en: 'Pick a serialization format. ONNX may fail for some estimators.',
    tr: 'Bir serileştirme formatı seçin. ONNX bazı kestiricilerde başarısız olabilir.',
    ku: 'Formatê serialîzasyonê hilbijêre. ONNX dibe li hin estimatoran sernekeve.',
    de: 'Wählen Sie ein Serialisierungsformat. ONNX kann bei manchen Schätzern fehlschlagen.',
    es: 'Elige un formato de serialización. ONNX puede fallar en algunos estimadores.',
    ru: 'Выберите формат сериализации. ONNX может не работать для некоторых оценщиков.',
    fr: 'Choisissez un format de sérialisation. ONNX peut échouer pour certains estimateurs.',
    it: 'Scegli un formato di serializzazione. ONNX può fallire con alcuni stimatori.',
  },
  exportOnnxNote: {
    en: 'ONNX may fail for some models. If you see errors, try joblib/pkl.',
    tr: 'ONNX bazı modeller için başarısız olabilir. Hata alırsanız joblib/pkl deneyin.',
    ku: 'ONNX dikare li hin modelan bisernekeve. Heke xeletî bibînî, joblib/pkl biceribîne.',
    de: 'ONNX kann bei einigen Modellen fehlschlagen. Nutzen Sie sonst joblib/pkl.',
    es: 'ONNX puede fallar en algunos modelos. Prueba joblib/pkl si ves errores.',
    ru: 'ONNX может не работать для некоторых моделей. Попробуйте joblib/pkl.',
    fr: 'ONNX peut échouer pour certains modèles. Essayez joblib/pkl en cas d’erreur.',
    it: 'ONNX può fallire per alcuni modelli. Prova joblib/pkl in caso di errori.',
  },
  howToUseExported: {
    en: 'How to use the exported model',
    tr: 'Dışa aktarılan model nasıl kullanılır',
    ku: 'Çawa modelê derxistî bi kar bîne',
    de: 'So verwenden Sie das exportierte Modell',
    es: 'Cómo usar el modelo exportado',
    ru: 'Как использовать экспортированную модель',
    fr: "Comment utiliser le modèle exporté",
    it: 'Come usare il modello esportato',
  },
  infoHowto: {
    en: 'Copy & paste into your environment. Make sure feature order matches training.',
    tr: 'Kopyalayıp ortamınıza yapıştırın. Özellik sırasının eğitimle aynı olduğundan emin olun.',
    ku: 'Ji bo erdnîgarê xwe kopî bikin û paste bikin. Rêza taybetmendiyan divê wekî fêrbûnê be.',
    de: 'Kopieren & einfügen. Achten Sie auf dieselbe Feature-Reihenfolge wie beim Training.',
    es: 'Copia y pega. Asegúrate del mismo orden de variables que en entrenamiento.',
    ru: 'Скопируйте и вставьте. Убедитесь, что порядок признаков совпадает с обучением.',
    fr: 'Copiez-collez. Veillez à garder le même ordre des variables qu’au training.',
    it: 'Copia e incolla. Stesso ordine delle feature del training.',
  },

  // ===== Metric descriptions (used as metric_*_desc) =====
  infoMetricFallback: {
    en: 'Metric explanation unavailable.',
    tr: 'Metrik açıklaması mevcut değil.',
    ku: 'Ravekirina metrîkê tune ye.',
    de: 'Keine Erklärung für diese Metrik verfügbar.',
    es: 'Sin explicación disponible para la métrica.',
    ru: 'Описание метрики недоступно.',
    fr: 'Explication de la métrique indisponible.',
    it: 'Spiegazione metrica non disponibile.',
  },

  // Classification
  metric_accuracy_desc: {
    en: 'Share of correct predictions (↑ better).',
    tr: 'Doğru tahmin oranı (↑ daha iyi).',
    ku: 'Rewşa pêşbîniyên rast (↑ baştir).',
    de: 'Anteil korrekter Vorhersagen (↑ besser).',
    es: 'Proporción de aciertos (↑ mejor).',
    ru: 'Доля верных предсказаний (↑ лучше).',
    fr: 'Part des prédictions correctes (↑ mieux).',
    it: 'Quota di predizioni corrette (↑ meglio).',
  },
  metric_balanced_accuracy_desc: {
    en: 'Average recall across classes (handles imbalance).',
    tr: 'Sınıflar arası ortalama duyarlılık (dengesizliğe dayanıklı).',
    ku: 'Navînê bîr anînê di nav sinifan de (ji nabe denghewariya daneyan).',
    de: 'Durchschnittlicher Recall über Klassen (robust ggü. Imbalance).',
    es: 'Recall medio por clase (maneja desbalance).',
    ru: 'Средний полнота по классам (устойчив к дисбалансу).',
    fr: 'Rappel moyen sur classes (gère le déséquilibre).',
    it: 'Richiamo medio tra classi (gestisce squilibrio).',
  },
  metric_precision_desc: {
    en: 'Correct positives among predicted positives.',
    tr: 'Pozitif tahminlerin ne kadarının doğru olduğu.',
    ku: 'Di pozîtîfên pêşbînîkirî de çend rast in.',
    de: 'Korrekte Positive unter vorhergesagten Positiven.',
    es: 'Positivos correctos entre los predichos.',
    ru: 'Доля истинных положительных среди предсказанных положительных.',
    fr: 'Positifs corrects parmi les prédits.',
    it: 'Positivi corretti tra i predetti.',
  },
  metric_recall_desc: {
    en: 'Found positives among all actual positives.',
    tr: 'Gerçek pozitiflerin ne kadarının bulunduğu.',
    ku: 'Ji hemû pozîtîfên rast de çend hatine dîtin.',
    de: 'Gefundene Positive unter allen tatsächlichen Positiven.',
    es: 'Positivos detectados entre los reales.',
    ru: 'Доля найденных положительных среди всех истинных.',
    fr: 'Positifs trouvés parmi tous les réels.',
    it: 'Positivi trovati tra i reali.',
  },
  metric_f1_desc: {
    en: 'Harmonic mean of precision and recall.',
    tr: 'Kesinlik ve duyarlılığın harmonik ortalaması.',
    ku: 'Navînê harmonîk a precision û recall.',
    de: 'Harmonisches Mittel aus Präzision und Recall.',
    es: 'Media armónica de precisión y recall.',
    ru: 'Гармоническое среднее precision и recall.',
    fr: 'Moyenne harmonique précision/rappel.',
    it: 'Media armonica di precision e recall.',
  },
  metric_roc_auc_desc: {
    en: 'Area under ROC curve (↑ better).',
    tr: 'ROC eğrisi altındaki alan (↑ daha iyi).',
    ku: 'Qada bin xêza ROC (↑ baştir).',
    de: 'Fläche unter ROC (↑ besser).',
    es: 'Área bajo la ROC (↑ mejor).',
    ru: 'Площадь под ROC-кривой (↑ лучше).',
    fr: 'Aire sous la courbe ROC (↑ mieux).',
    it: 'Area sotto la ROC (↑ meglio).',
  },
  metric_pr_auc_desc: {
    en: 'Area under precision–recall curve.',
    tr: 'Kesinlik-duyarlılık eğrisi altındaki alan.',
    ku: 'Qada bin xêza precision–recall.',
    de: 'Fläche unter PR-Kurve.',
    es: 'Área bajo la curva precisión–recobrado.',
    ru: 'Площадь под PR-кривой.',
    fr: 'Aire sous la courbe précision–rappel.',
    it: 'Area sotto la curva PR.',
  },
  metric_log_loss_desc: {
    en: 'Cross-entropy loss (↓ better).',
    tr: 'Çapraz entropi kaybı (↓ daha iyi).',
    ku: 'Ziyanê cross-entropy (↓ baştir).',
    de: 'Kreuzentropie-Verlust (↓ besser).',
    es: 'Pérdida de entropía cruzada (↓ mejor).',
    ru: 'Логистическая потеря (↓ лучше).',
    fr: "Perte d'entropie croisée (↓ mieux).",
    it: 'Perdita a entropia incrociata (↓ meglio).',
  },
  metric_mcc_desc: {
    en: 'Matthews correlation coefficient (−1..1).',
    tr: 'Matthews korelasyon katsayısı (−1..1).',
    ku: 'Koefîsyenta têkilî ya Matthews (−1..1).',
    de: 'Matthews-Korrelationskoeffizient (−1..1).',
    es: 'Coef. de correlación de Matthews (−1..1).',
    ru: 'Коэф. корреляции Мэттьюса (−1..1).',
    fr: 'Coefficient de corrélation de Matthews (−1..1).',
    it: 'Coefficiente di correlazione di Matthews (−1..1).',
  },

  // Regression
  metric_r2_desc: {
    en: 'Explained variance ratio (↑ better).',
    tr: 'Açıklanan varyans oranı (↑ daha iyi).',
    ku: 'Rêjeya varîansê ya şirove kirî (↑ baştir).',
    de: 'Erklärte Varianz (↑ besser).',
    es: 'Varianza explicada (↑ mejor).',
    ru: 'Доля объяснённой дисперсии (↑ лучше).',
    fr: 'Variance expliquée (↑ mieux).',
    it: 'Varianza spiegata (↑ meglio).',
  },
  metric_rmse_desc: {
    en: 'Root mean squared error (↓ better).',
    tr: 'Kök ortalama kare hata (↓ daha iyi).',
    ku: 'Kokê çewtiya kare ya navîn (↓ baştir).',
    de: 'Wurzel-MSE (↓ besser).',
    es: 'Raíz del error cuadrático medio (↓ mejor).',
    ru: 'КОРС (RMSE) (↓ лучше).',
    fr: 'Racine de l’erreur quadratique moyenne (↓ mieux).',
    it: 'Radice MSE (↓ meglio).',
  },
  metric_mae_desc: {
    en: 'Mean absolute error (↓ better).',
    tr: 'Ortalama mutlak hata (↓ daha iyi).',
    ku: 'Navînê çewtiya tevahî (↓ baştir).',
    de: 'Mittlerer absoluter Fehler (↓ besser).',
    es: 'Error absoluto medio (↓ mejor).',
    ru: 'Средняя абсолютная ошибка (↓ лучше).',
    fr: 'Erreur absolue moyenne (↓ mieux).',
    it: 'Errore assoluto medio (↓ meglio).',
  },
  metric_mse_desc: {
    en: 'Mean squared error (↓ better).',
    tr: 'Ortalama kare hata (↓ daha iyi).',
    ku: 'Navînê çewtiya kare (↓ baştir).',
    de: 'Mittlerer quadratischer Fehler (↓ besser).',
    es: 'Error cuadrático medio (↓ mejor).',
    ru: 'Среднеквадратичная ошибка (↓ лучше).',
    fr: 'Erreur quadratique moyenne (↓ mieux).',
    it: 'Errore quadratico medio (↓ meglio).',
  },
  metric_mape_desc: {
    en: 'Mean absolute percentage error (↓ better).',
    tr: 'Ortalama mutlak yüzde hata (↓ daha iyi).',
    ku: 'Navînê sedî çewtiya tevahî (↓ baştir).',
    de: 'Mittlerer absoluter prozentualer Fehler (↓ besser).',
    es: 'Error porcentual absoluto medio (↓ mejor).',
    ru: 'Средняя абсолютная процентная ошибка (↓ лучше).',
    fr: 'Erreur absolue moyenne en pourcentage (↓ mieux).',
    it: 'Errore percentuale assoluto medio (↓ meglio).',
  },
  metric_explained_variance_desc: {
    en: 'Variance proportion captured by the model (↑ better).',
    tr: 'Modelin yakaladığı varyans oranı (↑ daha iyi).',
    ku: 'Rêjeya varîansê ku model digire (↑ baştir).',
    de: 'Vom Modell erfasster Varianzanteil (↑ besser).',
    es: 'Proporción de varianza capturada por el modelo (↑ mejor).',
    ru: 'Доля дисперсии, объясняемая моделью (↑ лучше).',
    fr: 'Proportion de variance expliquée par le modèle (↑ mieux).',
    it: 'Quota di varianza spiegata dal modello (↑ meglio).',
  },

  // Clustering
  metric_silhouette_score_desc: {
    en: 'Cohesion vs. separation of clusters (−1..1, ↑ better).',
    tr: 'Kümelerin birlikteliği/ayrışması (−1..1, ↑ daha iyi).',
    ku: 'Yekvᵉtî û cuda bûn a koman (−1..1, ↑ baştir).',
    de: 'Kohäsion vs. Trennung der Cluster (−1..1, ↑ besser).',
    es: 'Cohesión vs. separación de clústeres (−1..1, ↑ mejor).',
    ru: 'Силуэт: сплочённость и разделение кластеров (−1..1, ↑ лучше).',
    fr: 'Cohésion vs. séparation des clusters (−1..1, ↑ mieux).',
    it: 'Coe­sione vs. separazione dei cluster (−1..1, ↑ meglio).',
  },
  metric_calinski_harabasz_desc: {
    en: 'Between/within cluster variance ratio (↑ better).',
    tr: 'Küme içi/dışı varyans oranı (↑ daha iyi).',
    ku: 'Rêjeya varîansê ya nav-kom û di navbera koman de (↑ baştir).',
    de: 'Varianzverhältnis zwischen/innerhalb Clustern (↑ besser).',
    es: 'Varianza entre/dentro de clústeres (↑ mejor).',
    ru: 'Индекс Калински–Харабаша (↑ лучше).',
    fr: 'Rapport de variance inter/intra-cluster (↑ mieux).',
    it: 'Rapporto varianza inter/intra-cluster (↑ meglio).',
  },
  metric_davies_bouldin_desc: {
    en: 'Average cluster similarity (↓ better).',
    tr: 'Ortalama küme benzerliği (↓ daha iyi).',
    ku: 'Hevgirtina koman ya navîn (↓ baştir).',
    de: 'Durchschnittliche Cluster-Ähnlichkeit (↓ besser).',
    es: 'Similitud media entre clústeres (↓ mejor).',
    ru: 'Средняя близость кластеров (↓ лучше).',
    fr: 'Similarité moyenne des clusters (↓ mieux).',
    it: 'Somiglianza media dei cluster (↓ meglio).',
  },
  metric_inertia_desc: {
    en: 'Sum of squared distances to cluster centers (↓ better).',
    tr: 'Küme merkezlerine kareli uzaklıkların toplamı (↓ daha iyi).',
    ku: 'Koma navendên dûrîyên kare yên hevdu (↓ baştir).',
    de: 'Summe quadr. Distanzen zu Clusterzentren (↓ besser).',
    es: 'Suma de distancias cuadráticas a centros (↓ mejor).',
    ru: 'Сумма квадратов расстояний до центров (↓ лучше).',
    fr: 'Somme des distances au carré aux centres (↓ mieux).',
    it: 'Somma distanze quadrate ai centri (↓ meglio).',
  },
  metric_n_clusters_desc: {
    en: 'Number of clusters formed (neutral).',
    tr: 'Oluşan küme sayısı (nötr).',
    ku: 'Hejmara koman (navbend).',
    de: 'Anzahl gebildeter Cluster (neutral).',
    es: 'Número de clústeres formados (neutral).',
    ru: 'Число кластеров (нейтр.).',
    fr: 'Nombre de clusters formés (neutre).',
    it: 'Numero di cluster formati (neutro).',
  },
  metric_min_cluster_size_desc: {
    en: 'Smallest cluster size (neutral).',
    tr: 'En küçük küme boyutu (nötr).',
    ku: 'Mezinahiya herî biçûk a koma (navbend).',
    de: 'Kleinste Clustergröße (neutral).',
    es: 'Tamaño mínimo de clúster (neutral).',
    ru: 'Размер наименьшего кластера (нейтр.).',
    fr: 'Taille minimale de cluster (neutre).',
    it: 'Dimensione minima cluster (neutro).',
  },
  metric_max_cluster_size_desc: {
    en: 'Largest cluster size (neutral).',
    tr: 'En büyük küme boyutu (nötr).',
    ku: 'Mezinahiya herî mezin a koma (navbend).',
    de: 'Größte Clustergröße (neutral).',
    es: 'Tamaño máximo de clúster (neutral).',
    ru: 'Размер наибольшего кластера (нейтр.).',
    fr: 'Taille maximale de cluster (neutre).',
    it: 'Dimensione massima cluster (neutro).',
  },
  metric_avg_cluster_size_desc: {
    en: 'Average cluster size (neutral).',
    tr: 'Ortalama küme boyutu (nötr).',
    ku: 'Mezinahiya navîn a koman (navbend).',
    de: 'Durchschnittliche Clustergröße (neutral).',
    es: 'Tamaño medio de clúster (neutral).',
    ru: 'Средний размер кластера (нейтр.).',
    fr: 'Taille moyenne de cluster (neutre).',
    it: 'Dimensione media cluster (neutro).',
  },
  metric_noise_ratio_desc: {
    en: 'Share of points labeled as noise (↓ better).',
    tr: 'Gürültü olarak etiketlenen noktaların oranı (↓ daha iyi).',
    ku: 'Rêjeya xalên wek qirêj hate nîşankirin (↓ baştir).',
    de: 'Anteil als Rauschen markierter Punkte (↓ besser).',
    es: 'Proporción de puntos ruido (↓ mejor).',
    ru: 'Доля точек-шумов (↓ лучше).',
    fr: 'Part des points étiquetés bruit (↓ mieux).',
    it: 'Quota di punti rumore (↓ meglio).',
  },
  // ==== Training step (add inside `translations`) ====
trainingSubtitle: {
  en: 'Configure the task, pick models, and start training',
  tr: 'Görevi yapılandırın, modelleri seçin ve eğitimi başlatın',
  ku: 'Peywirê saz bike, modelan hilbijêre û fêrkirinê dest pê bike',
  de: 'Aufgabe konfigurieren, Modelle wählen und Training starten',
  es: 'Configura la tarea, elige modelos y comienza el entrenamiento',
  ru: 'Настройте задачу, выберите модели и запустите обучение',
  fr: 'Configurez la tâche, choisissez des modèles et lancez l’entraînement',
  it: 'Configura il task, scegli i modelli e avvia il training',
},
infoTrainingOverview: {
  en: 'Select target, problem type, models and validation settings to train.',
  tr: 'Eğitim için hedef sütunu, problem türünü, modelleri ve doğrulama ayarlarını seçin.',
  ku: 'Ji bo fêrkirinê stûna hedef, tîpa pirsgirêkê, model û mîhengên rastandinê hilbijêre.',
  de: 'Wählen Sie Zielspalte, Problemtyp, Modelle und Validierungseinstellungen für das Training.',
  es: 'Elige la columna objetivo, tipo de problema, modelos y validación para entrenar.',
  ru: 'Выберите целевой столбец, тип задачи, модели и настройки валидации для обучения.',
  fr: 'Choisissez la colonne cible, le type de problème, les modèles et la validation pour entraîner.',
  it: 'Seleziona colonna target, tipo di problema, modelli e validazione per il training.',
},

problemConfiguration: {
  en: 'Problem Configuration',
  tr: 'Problem Yapılandırması',
  ku: 'Sazkirina Pirsgirêkê',
  de: 'Problemlayout',
  es: 'Configuración del problema',
  ru: 'Настройка задачи',
  fr: 'Configuration du problème',
  it: 'Configurazione del problema',
},
selectTargetColumn: {
  en: 'Select target column',
  tr: 'Hedef sütunu seçin',
  ku: 'Stûna hedef hilbijêre',
  de: 'Zielspalte auswählen',
  es: 'Selecciona la columna objetivo',
  ru: 'Выберите целевую колонку',
  fr: 'Sélectionnez la colonne cible',
  it: 'Seleziona la colonna target',
},
infoTargetColumn: {
  en: 'Column you want the model to predict. For clustering, you may leave it empty.',
  tr: 'Modelin tahmin etmesini istediğiniz sütun. Kümeleme için boş bırakabilirsiniz.',
  ku: 'Stûna ku dixwazî model pêşbînî bike. Ji bo clustering dikare vala bimîne.',
  de: 'Spalte, die das Modell vorhersagen soll. Für Clustering kann sie leer bleiben.',
  es: 'Columna que el modelo debe predecir. En clustering puede quedar vacía.',
  ru: 'Столбец, значение которого модель должна предсказывать. Для кластеризации можно оставить пустым.',
  fr: 'Colonne que le modèle doit prédire. Pour le clustering, peut rester vide.',
  it: 'Colonna che il modello deve predire. Per il clustering può restare vuota.',
},

// ⛔ problemTypeLabel burada TANIMLANMIYOR — üstteki mevcut anahtarı kullanın.
autoDetect: {
  en: 'Auto-detect',
  tr: 'Otomatik algıla',
  ku: 'Xweber bixwîne',
  de: 'Automatisch erkennen',
  es: 'Detectar automáticamente',
  ru: 'Определить автоматически',
  fr: 'Détection automatique',
  it: 'Rilevazione automatica',
},
classification: {
  en: 'Classification',
  tr: 'Sınıflandırma',
  ku: 'Sınıflandîn',
  de: 'Klassifikation',
  es: 'Clasificación',
  ru: 'Классификация',
  fr: 'Classification',
  it: 'Classificazione',
},
regression: {
  en: 'Regression',
  tr: 'Regresyon',
  ku: 'Regresyon',
  de: 'Regression',
  es: 'Regresión',
  ru: 'Регрессия',
  fr: 'Régression',
  it: 'Regressione',
},
clustering: {
  en: 'Clustering',
  tr: 'Kümeleme',
  ku: 'Koman kirin',
  de: 'Clustering',
  es: 'Clustering',
  ru: 'Кластеризация',
  fr: 'Clustering',
  it: 'Clustering',
},
detected: {
  en: 'Detected',
  tr: 'Algılandı',
  ku: 'Hat nasîn',
  de: 'Erkannt',
  es: 'Detectado',
  ru: 'Определено',
  fr: 'Détecté',
  it: 'Rilevato',
},
infoProblemType: {
  en: 'Choose the learning task. Auto tries to infer it from the target.',
  tr: 'Öğrenme görevini seçin. Otomatik, hedeften tahmin etmeye çalışır.',
  ku: 'Çalakiya fêr bûnê hilbijêre. Auto hewldide ji armancê berhemîne.',
  de: 'Wählen Sie die Lernaufgabe. Auto versucht sie aus dem Ziel abzuleiten.',
  es: 'Elige la tarea de aprendizaje. Auto intenta inferirla del objetivo.',
  ru: 'Выберите тип задачи. Auto пытается вывести его по цели.',
  fr: 'Choisissez la tâche d’apprentissage. Auto tente de l’inférer de la cible.',
  it: 'Scegli il tipo di task. Auto prova a inferirlo dal target.',
},

modelSelection: {
  en: 'Model Selection',
  tr: 'Model Seçimi',
  ku: 'Hilbijartina Modelê',
  de: 'Modellauswahl',
  es: 'Selección de modelo',
  ru: 'Выбор модели',
  fr: 'Sélection du modèle',
  it: 'Selezione del modello',
},
infoModelSelection: {
  en: 'Pick one or more algorithms to train for the chosen task.',
  tr: 'Seçili görev için eğitilecek bir veya daha fazla algoritma seçin.',
  ku: 'Ji bo peywirê yek an zêdetir algoritmên fêrkirinê hilbijêre.',
  de: 'Wählen Sie einen oder mehrere Algorithmen für die Aufgabe.',
  es: 'Elige uno o varios algoritmos para entrenar.',
  ru: 'Выберите один или несколько алгоритмов для обучения.',
  fr: 'Choisissez un ou plusieurs algorithmes à entraîner.',
  it: 'Scegli uno o più algoritmi da addestrare.',
},
pleaseSelectAtLeastOneModel: {
  en: 'Please select at least one model.',
  tr: 'Lütfen en az bir model seçin.',
  ku: 'Ji kerema xwe herî kêm yek model hilbijêre.',
  de: 'Bitte mindestens ein Modell auswählen.',
  es: 'Selecciona al menos un modelo.',
  ru: 'Выберите как минимум одну модель.',
  fr: 'Veuillez sélectionner au moins un modèle.',
  it: 'Seleziona almeno un modello.',
},

validationSettings: {
  en: 'Validation Settings',
  tr: 'Doğrulama Ayarları',
  ku: 'Mîhengên Rastandinê',
  de: 'Validierungseinstellungen',
  es: 'Ajustes de validación',
  ru: 'Настройки валидации',
  fr: 'Paramètres de validation',
  it: 'Impostazioni di validazione',
},
infoValidationSettings: {
  en: 'Choose how to evaluate models: simple holdout or K-fold cross-validation.',
  tr: 'Modelleri nasıl değerlendireceğinizi seçin: basit holdout veya K-katlı çapraz doğrulama.',
  ku: 'Hilbijêre ka model çawa têne nirxandin: holdout hêsan an K-fold cross-validation.',
  de: 'Wählen Sie Holdout oder K-fache Kreuzvalidierung.',
  es: 'Elige holdout simple o validación cruzada K-fold.',
  ru: 'Выберите holdout или K-блочную кросс-валидацию.',
  fr: 'Choisissez holdout simple ou validation croisée K-fold.',
  it: 'Scegli holdout o cross-validation a K fold.',
},
validationMethod: {
  en: 'Validation Method',
  tr: 'Doğrulama Yöntemi',
  ku: 'Rêbaza Rastandinê',
  de: 'Validierungsmethode',
  es: 'Método de validación',
  ru: 'Метод валидации',
  fr: 'Méthode de validation',
  it: 'Metodo di validazione',
},
trainTestSplit: {
  en: 'Train/Test Split',
  tr: 'Eğitim/Test Ayrımı',
  ku: 'Veqetandina Train/Test',
  de: 'Train/Test-Split',
  es: 'División Train/Test',
  ru: 'Разбиение Train/Test',
  fr: 'Séparation Train/Test',
  it: 'Suddivisione Train/Test',
},
crossValidation: {
  en: 'Cross-Validation',
  tr: 'Çapraz Doğrulama',
  ku: 'Cross-Validation',
  de: 'Kreuzvalidierung',
  es: 'Validación cruzada',
  ru: 'Кросс-валидация',
  fr: 'Validation croisée',
  it: 'Validazione incrociata',
},
testSize: {
  en: 'Test Size',
  tr: 'Test Oranı',
  ku: 'Rêjeya Testê',
  de: 'Testanteil',
  es: 'Tamaño de test',
  ru: 'Доля тестовой выборки',
  fr: 'Taille du test',
  it: 'Dimensione test',
},
infoTestSize: {
  en: 'Fraction of data held out for testing (0.1–0.5 typical).',
  tr: 'Test için ayrılan veri oranı (genellikle 0.1–0.5).',
  ku: 'Beşa daneyan ji bo testê tê veqetandin (0.1–0.5).',
  de: 'Datenanteil für den Test (typisch 0,1–0,5).',
  es: 'Fracción reservada para test (típico 0.1–0.5).',
  ru: 'Доля данных для теста (обычно 0.1–0.5).',
  fr: 'Part des données réservée au test (0,1–0,5).',
  it: 'Frazione di dati per il test (0,1–0,5).',
},
cvFolds: {
  en: 'CV Folds',
  tr: 'CV Kat Sayısı',
  ku: 'Hejmara katên CV',
  de: 'CV-Folds',
  es: 'Folds de CV',
  ru: 'Число фолдов',
  fr: 'Nombre de folds CV',
  it: 'Folds CV',
},
infoCvFolds: {
  en: 'Number of folds for K-fold cross-validation (3–10 typical).',
  tr: 'K-katlı çapraz doğrulamada kat sayısı (genelde 3–10).',
  ku: 'Hejmara katan ji bo K-fold cross-validation (3–10).',
  de: 'Anzahl der Folds für K-fache Kreuzvalidierung (typisch 3–10).',
  es: 'Número de folds en la validación cruzada K-fold (típico 3–10).',
  ru: 'Число фолдов в K-fold кросс-валидации (обычно 3–10).',
  fr: 'Nombre de folds pour la validation croisée K-fold (3–10).',
  it: 'Numero di fold per la K-fold (tipico 3–10).',
},

trainingSummary: {
  en: 'Training Summary',
  tr: 'Eğitim Özeti',
  ku: 'Kurteya Fêrkirinê',
  de: 'Trainingsübersicht',
  es: 'Resumen de entrenamiento',
  ru: 'Итоги обучения',
  fr: "Résumé d'entraînement",
  it: 'Riepilogo training',
},
datasetShape: {
  en: 'Dataset Shape',
  tr: 'Veri Kümesi Boyutu',
  ku: 'Şêwaza Daneyê',
  de: 'Datensatzform',
  es: 'Forma del dataset',
  ru: 'Размерность набора',
  fr: 'Taille du jeu de données',
  it: 'Forma del dataset',
},
features: {
  en: 'Features',
  tr: 'Özellik',
  ku: 'Taybetmendî',
  de: 'Merkmale',
  es: 'Características',
  ru: 'Признаки',
  fr: 'Variables',
  it: 'Feature',
},
samples: {
  en: 'Samples',
  tr: 'Örnek',
  ku: 'Mînak',
  de: 'Beispiele',
  es: 'Muestras',
  ru: 'Образцы',
  fr: 'Échantillons',
  it: 'Campioni',
},
modelsSelected: {
  en: 'Models Selected',
  tr: 'Seçilen Modeller',
  ku: 'Modelên Hilbijartî',
  de: 'Ausgewählte Modelle',
  es: 'Modelos seleccionados',
  ru: 'Выбранные модели',
  fr: 'Modèles sélectionnés',
  it: 'Modelli selezionati',
},
none: {
  en: 'None',
  tr: 'Yok',
  ku: 'Tune',
  de: 'Keine',
  es: 'Ninguno',
  ru: 'Нет',
  fr: 'Aucun',
  it: 'Nessuno',
},

train: {
  en: 'Train',
  tr: 'Eğit',
  ku: 'Fêr bike',
  de: 'Trainieren',
  es: 'Entrenar',
  ru: 'Обучить',
  fr: 'Entraîner',
  it: 'Addestra',
},
modelsPlural: {
  en: 'models',
  tr: 'model',
  ku: 'model',
  de: 'Modelle',
  es: 'modelos',
  ru: 'моделей',
  fr: 'modèles',
  it: 'modelli',
},
modelsSingular: {
  en: 'model',
  tr: 'model',
  ku: 'model',
  de: 'Modell',
  es: 'modelo',
  ru: 'модель',
  fr: 'modèle',
  it: 'modello',
},
trainingInProgress: {
  en: 'Training in progress',
  tr: 'Eğitim sürüyor',
  ku: 'Fêrkirin li peyê ye',
  de: 'Training läuft',
  es: 'Entrenamiento en curso',
  ru: 'Обучение выполняется',
  fr: 'Entraînement en cours',
  it: 'Training in corso',
},
trainingSuccess: {
  en: 'Training completed successfully',
  tr: 'Eğitim başarıyla tamamlandı',
  ku: 'Fêrkirin bi serkeftî qediya',
  de: 'Training erfolgreich abgeschlossen',
  es: 'Entrenamiento completado con éxito',
  ru: 'Обучение успешно завершено',
  fr: "Entraînement terminé avec succès",
  it: 'Training completato con successo',
},
failedToTrainModels: {
  en: 'Failed to train models',
  tr: 'Modeller eğitilirken hata oluştu',
  ku: 'Nekir modelan fêr bikin',
  de: 'Training der Modelle fehlgeschlagen',
  es: 'Error al entrenar los modelos',
  ru: 'Не удалось обучить модели',
  fr: "Échec de l'entraînement des modèles",
  it: 'Impossibile addestrare i modelli',
},
databaseStorageLimitReached: {
  en: 'Sorry, the database storage limit has been reached. Please try again later.',
  tr: 'Üzgünüz, veritabanı depolama limitine ulaşıldı. Lütfen daha sonra tekrar deneyiniz.',
  ku: 'Bibore, sînorê hilanîna danegiran gihîştiye. Ji kerema xwe paşê dîsa biceribîne.',
  de: 'Entschuldigung, die Datenbankspeichergrenze wurde erreicht. Bitte versuchen Sie es später erneut.',
  es: 'Lo sentimos, se ha alcanzado el límite de almacenamiento de la base de datos. Por favor, inténtelo más tarde.',
  ru: 'Извините, достигнут лимит хранилища базы данных. Пожалуйста, попробуйте позже.',
  fr: "Désolé, la limite de stockage de la base de données a été atteinte. Veuillez réessayer plus tard.",
  it: 'Spiacenti, è stato raggiunto il limite di archiviazione del database. Riprova più tardi.',
},
databaseErrorGeneral: {
  en: 'Sorry, we cannot complete your request at this time. Please try again later.',
  tr: 'Üzgünüz, işleminizi şu anda gerçekleştiremiyoruz. Lütfen daha sonra tekrar deneyiniz.',
  ku: 'Bibore, em nikarîn daxwaza te niha temam bikin. Ji kerema xwe paşê dîsa biceribîne.',
  de: 'Entschuldigung, wir können Ihre Anfrage derzeit nicht bearbeiten. Bitte versuchen Sie es später erneut.',
  es: 'Lo sentimos, no podemos completar su solicitud en este momento. Por favor, inténtelo más tarde.',
  ru: 'Извините, мы не можем выполнить ваш запрос в данный момент. Пожалуйста, попробуйте позже.',
  fr: 'Désolé, nous ne pouvons pas traiter votre demande pour le moment. Veuillez réessayer plus tard.',
  it: 'Spiacenti, al momento non possiamo completare la tua richiesta. Riprova più tardi.',
}
};

export const languages = [
  { code: 'en' as LanguageCode, name: 'English' },
  { code: 'tr' as LanguageCode, name: 'Türkçe' },
  { code: 'ku' as LanguageCode, name: 'Kurdî' },
  { code: 'de' as LanguageCode, name: 'Deutsch' },
  { code: 'es' as LanguageCode, name: 'Español' },
  { code: 'ru' as LanguageCode, name: 'Русский' },
  { code: 'fr' as LanguageCode, name: 'Français' },
  { code: 'it' as LanguageCode, name: 'Italiano' },
];

export const useLanguage = () => {
  const [currentLanguage, setCurrentLanguage] = useState<LanguageCode>('en');
  const [isLoaded, setIsLoaded] = useState(false);

  const t = (key: string): string => {
    return translations[key]?.[currentLanguage] || translations[key]?.en || key;
  };

  const changeLanguage = (lang: LanguageCode) => {
    setCurrentLanguage(lang);
    localStorage.setItem('GroveML-language', lang);
    setIsLoaded(prev => !prev);
  };

  useEffect(() => {
    const saved = localStorage.getItem('GroveML-language') as LanguageCode;
    if (saved && languages.find(l => l.code === saved)) {
      setCurrentLanguage(saved);
    }
    setIsLoaded(true);
  }, []);

  return { currentLanguage, changeLanguage, t, isLoaded };
};
